// Generated by dust2 (version 0.3.28) - do not edit

// Generated by odin2 (version 0.3.43) - do not edit
#include <dust2/common.hpp>
// [[dust2::class(simex)]]
// [[dust2::time_type(discrete)]]
// [[dust2::has_compare()]]
// [[dust2::parameter(n_age, type = "int", rank = 0, required = TRUE, constant = TRUE)]]
// [[dust2::parameter(N, type = "real_type", rank = 0, required = TRUE, constant = FALSE)]]
// [[dust2::parameter(hosp_capacity, type = "real_type", rank = 0, required = TRUE, constant = FALSE)]]
// [[dust2::parameter(vax_rate, type = "real_type", rank = 0, required = TRUE, constant = FALSE)]]
// [[dust2::parameter(vax_prioritised, type = "real_type", rank = 0, required = TRUE, constant = FALSE)]]
// [[dust2::parameter(hosp_prioritised, type = "real_type", rank = 0, required = TRUE, constant = FALSE)]]
// [[dust2::parameter(vax_infectiousness, type = "real_type", rank = 0, required = TRUE, constant = FALSE)]]
// [[dust2::parameter(vax_infection, type = "real_type", rank = 0, required = TRUE, constant = FALSE)]]
// [[dust2::parameter(vax_hosp, type = "real_type", rank = 0, required = TRUE, constant = FALSE)]]
// [[dust2::parameter(vax_death, type = "real_type", rank = 0, required = TRUE, constant = FALSE)]]
// [[dust2::parameter(prop_hosp, type = "real_type", rank = 1, required = TRUE, constant = FALSE)]]
// [[dust2::parameter(hosp_mortality, type = "real_type", rank = 1, required = TRUE, constant = FALSE)]]
// [[dust2::parameter(unhosp_mortality, type = "real_type", rank = 1, required = TRUE, constant = FALSE)]]
// [[dust2::parameter(hosp_duration, type = "real_type", rank = 1, required = TRUE, constant = FALSE)]]
// [[dust2::parameter(comm_mortality, type = "real_type", rank = 1, required = TRUE, constant = FALSE)]]
// [[dust2::parameter(symptomatic_period, type = "real_type", rank = 0, required = TRUE, constant = FALSE)]]
// [[dust2::parameter(incubation_period, type = "real_type", rank = 0, required = TRUE, constant = FALSE)]]
// [[dust2::parameter(p_trans, type = "real_type", rank = 0, required = TRUE, constant = FALSE)]]
// [[dust2::parameter(kappa_E, type = "real_type", rank = 2, required = TRUE, constant = FALSE)]]
// [[dust2::parameter(kappa_C, type = "real_type", rank = 2, required = TRUE, constant = FALSE)]]
// [[dust2::parameter(kappa_H, type = "real_type", rank = 2, required = TRUE, constant = FALSE)]]
// [[dust2::parameter(init_state, type = "real_type", rank = 2, required = TRUE, constant = FALSE)]]
class simex {
public:
  simex() = delete;
  using real_type = double;
  using rng_state_type = monty::random::generator<real_type>;
  struct shared_state {
    struct odin_internals_type {
      struct {
        dust2::packing state;
      } packing;
      struct {
        std::array<size_t, 24> state;
      } offset;
    } odin;
    struct dim_type {
      dust2::array::dimensions<1> Su;
      dust2::array::dimensions<2> kappa_E;
      dust2::array::dimensions<2> init_state;
    } dim;
    int n_age;
    real_type N;
    real_type hosp_capacity;
    real_type vax_rate;
    real_type vax_prioritised;
    real_type hosp_prioritised;
    real_type vax_infectiousness;
    real_type vax_infection;
    real_type vax_hosp;
    real_type vax_death;
    real_type symptomatic_period;
    real_type incubation_period;
    real_type p_trans;
    std::vector<real_type> prop_hosp;
    std::vector<real_type> hosp_mortality;
    std::vector<real_type> unhosp_mortality;
    std::vector<real_type> hosp_duration;
    std::vector<real_type> comm_mortality;
    std::vector<real_type> kappa_E;
    std::vector<real_type> kappa_C;
    std::vector<real_type> kappa_H;
    std::vector<real_type> init_state;
    std::vector<real_type> sigma_Eu;
    std::vector<real_type> eta_Eu;
    std::vector<real_type> sigma_Ev;
    std::vector<real_type> eta_Ev;
    std::vector<real_type> gamma_Cu;
    std::vector<real_type> mu_Cu;
    std::vector<real_type> gamma_Cv;
    std::vector<real_type> mu_Cv;
    std::vector<real_type> frac_Eu_to_Cu;
    std::vector<real_type> frac_Ev_to_Cv;
    std::vector<real_type> frac_Cu_to_R;
    std::vector<real_type> frac_Cv_to_R;
  };
  struct internal_state {
    std::vector<real_type> hosp_required;
    std::vector<real_type> lambda_Eu;
    std::vector<real_type> lambda_Ev;
    std::vector<real_type> lambda_Cu;
    std::vector<real_type> lambda_Cv;
    std::vector<real_type> lambda_Hu;
    std::vector<real_type> lambda_Hv;
    std::vector<real_type> hosp_rem;
    std::vector<real_type> lambda_E;
    std::vector<real_type> lambda_C;
    std::vector<real_type> lambda_H;
    std::vector<real_type> hospitalised;
    std::vector<real_type> p_Eu_exit;
    std::vector<real_type> p_Ev_exit;
    std::vector<real_type> p_Cu_exit;
    std::vector<real_type> p_Cv_exit;
    std::vector<real_type> lambda_u;
    std::vector<real_type> lambda_v;
    std::vector<real_type> total_hosp_mortality;
    std::vector<real_type> n_Eu_exit;
    std::vector<real_type> n_Ev_exit;
    std::vector<real_type> n_Cu_exit;
    std::vector<real_type> n_Cv_exit;
    std::vector<real_type> gamma_Hu;
    std::vector<real_type> mu_Hu;
    std::vector<real_type> gamma_Hv;
    std::vector<real_type> mu_Hv;
    std::vector<real_type> p_Su_to_Eu;
    std::vector<real_type> p_Sv_to_Ev;
    std::vector<real_type> n_Eu_to_Cu;
    std::vector<real_type> n_Ev_to_Cv;
    std::vector<real_type> n_Cu_to_Ru;
    std::vector<real_type> n_Cv_to_Rv;
    std::vector<real_type> p_Hu_exit;
    std::vector<real_type> p_Hv_exit;
    std::vector<real_type> frac_Hu_to_R;
    std::vector<real_type> frac_Hv_to_R;
    std::vector<real_type> n_Su_to_Eu;
    std::vector<real_type> n_Sv_to_Ev;
    std::vector<real_type> n_Eu_to_Hu;
    std::vector<real_type> n_Ev_to_Hv;
    std::vector<real_type> n_Cu_to_Du;
    std::vector<real_type> n_Cv_to_Dv;
    std::vector<real_type> n_Hu_exit;
    std::vector<real_type> n_Hv_exit;
    std::vector<real_type> Su_after_inf;
    std::vector<real_type> n_Hu_to_Ru;
    std::vector<real_type> n_Hv_to_Rv;
    std::vector<real_type> vax_rem;
    std::vector<real_type> n_Hu_to_Du;
    std::vector<real_type> n_Hv_to_Dv;
    std::vector<real_type> vax_target;
    std::vector<real_type> p_Su_to_Sv;
    std::vector<real_type> n_Su_to_Sv;
  };
  struct data_type {
    std::vector<real_type> E_reported;
  };
  static dust2::packing packing_state(const shared_state& shared) {
    return shared.odin.packing.state;
  }
  static shared_state build_shared(cpp11::list parameters) {
    shared_state::dim_type dim;
    const int n_age = dust2::r::read_int(parameters, "n_age");
    const real_type N = dust2::r::read_real(parameters, "N");
    const real_type hosp_capacity = dust2::r::read_real(parameters, "hosp_capacity");
    const real_type vax_rate = dust2::r::read_real(parameters, "vax_rate");
    const real_type vax_prioritised = dust2::r::read_real(parameters, "vax_prioritised");
    const real_type hosp_prioritised = dust2::r::read_real(parameters, "hosp_prioritised");
    const real_type vax_infectiousness = dust2::r::read_real(parameters, "vax_infectiousness");
    const real_type vax_infection = dust2::r::read_real(parameters, "vax_infection");
    const real_type vax_hosp = dust2::r::read_real(parameters, "vax_hosp");
    const real_type vax_death = dust2::r::read_real(parameters, "vax_death");
    const real_type symptomatic_period = dust2::r::read_real(parameters, "symptomatic_period");
    const real_type incubation_period = dust2::r::read_real(parameters, "incubation_period");
    const real_type p_trans = dust2::r::read_real(parameters, "p_trans");
    dim.Su.set({static_cast<size_t>(n_age)});
    dim.kappa_E.set({static_cast<size_t>(n_age), static_cast<size_t>(n_age)});
    dim.init_state.set({static_cast<size_t>(n_age), static_cast<size_t>(12)});
    std::vector<real_type> prop_hosp(dim.Su.size);
    dust2::r::read_real_array(parameters, dim.Su, prop_hosp.data(), "prop_hosp", true);
    std::vector<real_type> hosp_mortality(dim.Su.size);
    dust2::r::read_real_array(parameters, dim.Su, hosp_mortality.data(), "hosp_mortality", true);
    std::vector<real_type> unhosp_mortality(dim.Su.size);
    dust2::r::read_real_array(parameters, dim.Su, unhosp_mortality.data(), "unhosp_mortality", true);
    std::vector<real_type> hosp_duration(dim.Su.size);
    dust2::r::read_real_array(parameters, dim.Su, hosp_duration.data(), "hosp_duration", true);
    std::vector<real_type> comm_mortality(dim.Su.size);
    dust2::r::read_real_array(parameters, dim.Su, comm_mortality.data(), "comm_mortality", true);
    std::vector<real_type> kappa_E(dim.kappa_E.size);
    dust2::r::read_real_array(parameters, dim.kappa_E, kappa_E.data(), "kappa_E", true);
    std::vector<real_type> kappa_C(dim.kappa_E.size);
    dust2::r::read_real_array(parameters, dim.kappa_E, kappa_C.data(), "kappa_C", true);
    std::vector<real_type> kappa_H(dim.kappa_E.size);
    dust2::r::read_real_array(parameters, dim.kappa_E, kappa_H.data(), "kappa_H", true);
    std::vector<real_type> init_state(dim.init_state.size);
    dust2::r::read_real_array(parameters, dim.init_state, init_state.data(), "init_state", true);
    std::vector<real_type> sigma_Eu(dim.Su.size);
    for (size_t i = 1; i <= dim.Su.size; ++i) {
      sigma_Eu[i - 1] = (1 - prop_hosp[i - 1]) / incubation_period;
    }
    std::vector<real_type> eta_Eu(dim.Su.size);
    for (size_t i = 1; i <= dim.Su.size; ++i) {
      eta_Eu[i - 1] = prop_hosp[i - 1] / incubation_period;
    }
    std::vector<real_type> sigma_Ev(dim.Su.size);
    for (size_t i = 1; i <= dim.Su.size; ++i) {
      sigma_Ev[i - 1] = (1 - (1 - vax_hosp) * prop_hosp[i - 1]) / incubation_period;
    }
    std::vector<real_type> eta_Ev(dim.Su.size);
    for (size_t i = 1; i <= dim.Su.size; ++i) {
      eta_Ev[i - 1] = (1 - vax_hosp) * prop_hosp[i - 1] / incubation_period;
    }
    std::vector<real_type> gamma_Cu(dim.Su.size);
    for (size_t i = 1; i <= dim.Su.size; ++i) {
      gamma_Cu[i - 1] = (1 - comm_mortality[i - 1]) / symptomatic_period;
    }
    std::vector<real_type> mu_Cu(dim.Su.size);
    for (size_t i = 1; i <= dim.Su.size; ++i) {
      mu_Cu[i - 1] = comm_mortality[i - 1] / symptomatic_period;
    }
    std::vector<real_type> gamma_Cv(dim.Su.size);
    for (size_t i = 1; i <= dim.Su.size; ++i) {
      gamma_Cv[i - 1] = (1 - (1 - vax_death) * comm_mortality[i - 1]) / symptomatic_period;
    }
    std::vector<real_type> mu_Cv(dim.Su.size);
    for (size_t i = 1; i <= dim.Su.size; ++i) {
      mu_Cv[i - 1] = (1 - vax_death) * comm_mortality[i - 1] / symptomatic_period;
    }
    std::vector<real_type> frac_Eu_to_Cu(dim.Su.size);
    for (size_t i = 1; i <= dim.Su.size; ++i) {
      frac_Eu_to_Cu[i - 1] = ((sigma_Eu[i - 1] + eta_Eu[i - 1] > 0 ? sigma_Eu[i - 1] / (sigma_Eu[i - 1] + eta_Eu[i - 1]) : 0));
    }
    std::vector<real_type> frac_Ev_to_Cv(dim.Su.size);
    for (size_t i = 1; i <= dim.Su.size; ++i) {
      frac_Ev_to_Cv[i - 1] = ((sigma_Ev[i - 1] + eta_Ev[i - 1] > 0 ? sigma_Ev[i - 1] / (sigma_Ev[i - 1] + eta_Ev[i - 1]) : 0));
    }
    std::vector<real_type> frac_Cu_to_R(dim.Su.size);
    for (size_t i = 1; i <= dim.Su.size; ++i) {
      frac_Cu_to_R[i - 1] = ((gamma_Cu[i - 1] + mu_Cu[i - 1] > 0 ? gamma_Cu[i - 1] / (gamma_Cu[i - 1] + mu_Cu[i - 1]) : 0));
    }
    std::vector<real_type> frac_Cv_to_R(dim.Su.size);
    for (size_t i = 1; i <= dim.Su.size; ++i) {
      frac_Cv_to_R[i - 1] = ((gamma_Cv[i - 1] + mu_Cv[i - 1] > 0 ? gamma_Cv[i - 1] / (gamma_Cv[i - 1] + mu_Cv[i - 1]) : 0));
    }
    shared_state::odin_internals_type odin;
    odin.packing.state = dust2::packing{
      {"Su", std::vector<size_t>(dim.Su.dim.begin(), dim.Su.dim.end())},
      {"Eu", std::vector<size_t>(dim.Su.dim.begin(), dim.Su.dim.end())},
      {"Cu", std::vector<size_t>(dim.Su.dim.begin(), dim.Su.dim.end())},
      {"Hu", std::vector<size_t>(dim.Su.dim.begin(), dim.Su.dim.end())},
      {"Ru", std::vector<size_t>(dim.Su.dim.begin(), dim.Su.dim.end())},
      {"Du", std::vector<size_t>(dim.Su.dim.begin(), dim.Su.dim.end())},
      {"Sv", std::vector<size_t>(dim.Su.dim.begin(), dim.Su.dim.end())},
      {"Ev", std::vector<size_t>(dim.Su.dim.begin(), dim.Su.dim.end())},
      {"Cv", std::vector<size_t>(dim.Su.dim.begin(), dim.Su.dim.end())},
      {"Hv", std::vector<size_t>(dim.Su.dim.begin(), dim.Su.dim.end())},
      {"Rv", std::vector<size_t>(dim.Su.dim.begin(), dim.Su.dim.end())},
      {"Dv", std::vector<size_t>(dim.Su.dim.begin(), dim.Su.dim.end())},
      {"Su_i", std::vector<size_t>(dim.Su.dim.begin(), dim.Su.dim.end())},
      {"Eu_i", std::vector<size_t>(dim.Su.dim.begin(), dim.Su.dim.end())},
      {"Cu_i", std::vector<size_t>(dim.Su.dim.begin(), dim.Su.dim.end())},
      {"Hu_i", std::vector<size_t>(dim.Su.dim.begin(), dim.Su.dim.end())},
      {"Ru_i", std::vector<size_t>(dim.Su.dim.begin(), dim.Su.dim.end())},
      {"Du_i", std::vector<size_t>(dim.Su.dim.begin(), dim.Su.dim.end())},
      {"Sv_i", std::vector<size_t>(dim.Su.dim.begin(), dim.Su.dim.end())},
      {"Ev_i", std::vector<size_t>(dim.Su.dim.begin(), dim.Su.dim.end())},
      {"Cv_i", std::vector<size_t>(dim.Su.dim.begin(), dim.Su.dim.end())},
      {"Hv_i", std::vector<size_t>(dim.Su.dim.begin(), dim.Su.dim.end())},
      {"Rv_i", std::vector<size_t>(dim.Su.dim.begin(), dim.Su.dim.end())},
      {"Dv_i", std::vector<size_t>(dim.Su.dim.begin(), dim.Su.dim.end())}
    };
    odin.packing.state.copy_offset(odin.offset.state.begin());
    return shared_state{odin, dim, n_age, N, hosp_capacity, vax_rate, vax_prioritised, hosp_prioritised, vax_infectiousness, vax_infection, vax_hosp, vax_death, symptomatic_period, incubation_period, p_trans, prop_hosp, hosp_mortality, unhosp_mortality, hosp_duration, comm_mortality, kappa_E, kappa_C, kappa_H, init_state, sigma_Eu, eta_Eu, sigma_Ev, eta_Ev, gamma_Cu, mu_Cu, gamma_Cv, mu_Cv, frac_Eu_to_Cu, frac_Ev_to_Cv, frac_Cu_to_R, frac_Cv_to_R};
  }
  static internal_state build_internal(const shared_state& shared) {
    std::vector<real_type> hosp_required(shared.dim.Su.size);
    std::vector<real_type> lambda_Eu(shared.dim.kappa_E.size);
    std::vector<real_type> lambda_Ev(shared.dim.kappa_E.size);
    std::vector<real_type> lambda_Cu(shared.dim.kappa_E.size);
    std::vector<real_type> lambda_Cv(shared.dim.kappa_E.size);
    std::vector<real_type> lambda_Hu(shared.dim.kappa_E.size);
    std::vector<real_type> lambda_Hv(shared.dim.kappa_E.size);
    std::vector<real_type> hosp_rem(shared.dim.Su.size);
    std::vector<real_type> lambda_E(shared.dim.Su.size);
    std::vector<real_type> lambda_C(shared.dim.Su.size);
    std::vector<real_type> lambda_H(shared.dim.Su.size);
    std::vector<real_type> hospitalised(shared.dim.Su.size);
    std::vector<real_type> p_Eu_exit(shared.dim.Su.size);
    std::vector<real_type> p_Ev_exit(shared.dim.Su.size);
    std::vector<real_type> p_Cu_exit(shared.dim.Su.size);
    std::vector<real_type> p_Cv_exit(shared.dim.Su.size);
    std::vector<real_type> lambda_u(shared.dim.Su.size);
    std::vector<real_type> lambda_v(shared.dim.Su.size);
    std::vector<real_type> total_hosp_mortality(shared.dim.Su.size);
    std::vector<real_type> n_Eu_exit(shared.dim.Su.size);
    std::vector<real_type> n_Ev_exit(shared.dim.Su.size);
    std::vector<real_type> n_Cu_exit(shared.dim.Su.size);
    std::vector<real_type> n_Cv_exit(shared.dim.Su.size);
    std::vector<real_type> gamma_Hu(shared.dim.Su.size);
    std::vector<real_type> mu_Hu(shared.dim.Su.size);
    std::vector<real_type> gamma_Hv(shared.dim.Su.size);
    std::vector<real_type> mu_Hv(shared.dim.Su.size);
    std::vector<real_type> p_Su_to_Eu(shared.dim.Su.size);
    std::vector<real_type> p_Sv_to_Ev(shared.dim.Su.size);
    std::vector<real_type> n_Eu_to_Cu(shared.dim.Su.size);
    std::vector<real_type> n_Ev_to_Cv(shared.dim.Su.size);
    std::vector<real_type> n_Cu_to_Ru(shared.dim.Su.size);
    std::vector<real_type> n_Cv_to_Rv(shared.dim.Su.size);
    std::vector<real_type> p_Hu_exit(shared.dim.Su.size);
    std::vector<real_type> p_Hv_exit(shared.dim.Su.size);
    std::vector<real_type> frac_Hu_to_R(shared.dim.Su.size);
    std::vector<real_type> frac_Hv_to_R(shared.dim.Su.size);
    std::vector<real_type> n_Su_to_Eu(shared.dim.Su.size);
    std::vector<real_type> n_Sv_to_Ev(shared.dim.Su.size);
    std::vector<real_type> n_Eu_to_Hu(shared.dim.Su.size);
    std::vector<real_type> n_Ev_to_Hv(shared.dim.Su.size);
    std::vector<real_type> n_Cu_to_Du(shared.dim.Su.size);
    std::vector<real_type> n_Cv_to_Dv(shared.dim.Su.size);
    std::vector<real_type> n_Hu_exit(shared.dim.Su.size);
    std::vector<real_type> n_Hv_exit(shared.dim.Su.size);
    std::vector<real_type> Su_after_inf(shared.dim.Su.size);
    std::vector<real_type> n_Hu_to_Ru(shared.dim.Su.size);
    std::vector<real_type> n_Hv_to_Rv(shared.dim.Su.size);
    std::vector<real_type> vax_rem(shared.dim.Su.size);
    std::vector<real_type> n_Hu_to_Du(shared.dim.Su.size);
    std::vector<real_type> n_Hv_to_Dv(shared.dim.Su.size);
    std::vector<real_type> vax_target(shared.dim.Su.size);
    std::vector<real_type> p_Su_to_Sv(shared.dim.Su.size);
    std::vector<real_type> n_Su_to_Sv(shared.dim.Su.size);
    return internal_state{hosp_required, lambda_Eu, lambda_Ev, lambda_Cu, lambda_Cv, lambda_Hu, lambda_Hv, hosp_rem, lambda_E, lambda_C, lambda_H, hospitalised, p_Eu_exit, p_Ev_exit, p_Cu_exit, p_Cv_exit, lambda_u, lambda_v, total_hosp_mortality, n_Eu_exit, n_Ev_exit, n_Cu_exit, n_Cv_exit, gamma_Hu, mu_Hu, gamma_Hv, mu_Hv, p_Su_to_Eu, p_Sv_to_Ev, n_Eu_to_Cu, n_Ev_to_Cv, n_Cu_to_Ru, n_Cv_to_Rv, p_Hu_exit, p_Hv_exit, frac_Hu_to_R, frac_Hv_to_R, n_Su_to_Eu, n_Sv_to_Ev, n_Eu_to_Hu, n_Ev_to_Hv, n_Cu_to_Du, n_Cv_to_Dv, n_Hu_exit, n_Hv_exit, Su_after_inf, n_Hu_to_Ru, n_Hv_to_Rv, vax_rem, n_Hu_to_Du, n_Hv_to_Dv, vax_target, p_Su_to_Sv, n_Su_to_Sv};
  }
  static data_type build_data(cpp11::list data, const shared_state& shared) {
    auto E_reported = std::vector<real_type>(shared.dim.Su.size);
    dust2::r::read_real_array(data, shared.dim.Su, E_reported.data(), "E_reported", true);
    return data_type{E_reported};
  }
  static void update_shared(cpp11::list parameters, shared_state& shared) {
    shared.N = dust2::r::read_real(parameters, "N", shared.N);
    shared.hosp_capacity = dust2::r::read_real(parameters, "hosp_capacity", shared.hosp_capacity);
    shared.vax_rate = dust2::r::read_real(parameters, "vax_rate", shared.vax_rate);
    shared.vax_prioritised = dust2::r::read_real(parameters, "vax_prioritised", shared.vax_prioritised);
    shared.hosp_prioritised = dust2::r::read_real(parameters, "hosp_prioritised", shared.hosp_prioritised);
    shared.vax_infectiousness = dust2::r::read_real(parameters, "vax_infectiousness", shared.vax_infectiousness);
    shared.vax_infection = dust2::r::read_real(parameters, "vax_infection", shared.vax_infection);
    shared.vax_hosp = dust2::r::read_real(parameters, "vax_hosp", shared.vax_hosp);
    shared.vax_death = dust2::r::read_real(parameters, "vax_death", shared.vax_death);
    shared.symptomatic_period = dust2::r::read_real(parameters, "symptomatic_period", shared.symptomatic_period);
    shared.incubation_period = dust2::r::read_real(parameters, "incubation_period", shared.incubation_period);
    shared.p_trans = dust2::r::read_real(parameters, "p_trans", shared.p_trans);
    dust2::r::read_real_array(parameters, shared.dim.Su, shared.prop_hosp.data(), "prop_hosp", false);
    dust2::r::read_real_array(parameters, shared.dim.Su, shared.hosp_mortality.data(), "hosp_mortality", false);
    dust2::r::read_real_array(parameters, shared.dim.Su, shared.unhosp_mortality.data(), "unhosp_mortality", false);
    dust2::r::read_real_array(parameters, shared.dim.Su, shared.hosp_duration.data(), "hosp_duration", false);
    dust2::r::read_real_array(parameters, shared.dim.Su, shared.comm_mortality.data(), "comm_mortality", false);
    dust2::r::read_real_array(parameters, shared.dim.kappa_E, shared.kappa_E.data(), "kappa_E", false);
    dust2::r::read_real_array(parameters, shared.dim.kappa_E, shared.kappa_C.data(), "kappa_C", false);
    dust2::r::read_real_array(parameters, shared.dim.kappa_E, shared.kappa_H.data(), "kappa_H", false);
    dust2::r::read_real_array(parameters, shared.dim.init_state, shared.init_state.data(), "init_state", false);
    for (size_t i = 1; i <= shared.dim.Su.size; ++i) {
      shared.sigma_Eu[i - 1] = (1 - shared.prop_hosp[i - 1]) / shared.incubation_period;
    }
    for (size_t i = 1; i <= shared.dim.Su.size; ++i) {
      shared.eta_Eu[i - 1] = shared.prop_hosp[i - 1] / shared.incubation_period;
    }
    for (size_t i = 1; i <= shared.dim.Su.size; ++i) {
      shared.sigma_Ev[i - 1] = (1 - (1 - shared.vax_hosp) * shared.prop_hosp[i - 1]) / shared.incubation_period;
    }
    for (size_t i = 1; i <= shared.dim.Su.size; ++i) {
      shared.eta_Ev[i - 1] = (1 - shared.vax_hosp) * shared.prop_hosp[i - 1] / shared.incubation_period;
    }
    for (size_t i = 1; i <= shared.dim.Su.size; ++i) {
      shared.gamma_Cu[i - 1] = (1 - shared.comm_mortality[i - 1]) / shared.symptomatic_period;
    }
    for (size_t i = 1; i <= shared.dim.Su.size; ++i) {
      shared.mu_Cu[i - 1] = shared.comm_mortality[i - 1] / shared.symptomatic_period;
    }
    for (size_t i = 1; i <= shared.dim.Su.size; ++i) {
      shared.gamma_Cv[i - 1] = (1 - (1 - shared.vax_death) * shared.comm_mortality[i - 1]) / shared.symptomatic_period;
    }
    for (size_t i = 1; i <= shared.dim.Su.size; ++i) {
      shared.mu_Cv[i - 1] = (1 - shared.vax_death) * shared.comm_mortality[i - 1] / shared.symptomatic_period;
    }
    for (size_t i = 1; i <= shared.dim.Su.size; ++i) {
      shared.frac_Eu_to_Cu[i - 1] = ((shared.sigma_Eu[i - 1] + shared.eta_Eu[i - 1] > 0 ? shared.sigma_Eu[i - 1] / (shared.sigma_Eu[i - 1] + shared.eta_Eu[i - 1]) : 0));
    }
    for (size_t i = 1; i <= shared.dim.Su.size; ++i) {
      shared.frac_Ev_to_Cv[i - 1] = ((shared.sigma_Ev[i - 1] + shared.eta_Ev[i - 1] > 0 ? shared.sigma_Ev[i - 1] / (shared.sigma_Ev[i - 1] + shared.eta_Ev[i - 1]) : 0));
    }
    for (size_t i = 1; i <= shared.dim.Su.size; ++i) {
      shared.frac_Cu_to_R[i - 1] = ((shared.gamma_Cu[i - 1] + shared.mu_Cu[i - 1] > 0 ? shared.gamma_Cu[i - 1] / (shared.gamma_Cu[i - 1] + shared.mu_Cu[i - 1]) : 0));
    }
    for (size_t i = 1; i <= shared.dim.Su.size; ++i) {
      shared.frac_Cv_to_R[i - 1] = ((shared.gamma_Cv[i - 1] + shared.mu_Cv[i - 1] > 0 ? shared.gamma_Cv[i - 1] / (shared.gamma_Cv[i - 1] + shared.mu_Cv[i - 1]) : 0));
    }
  }
  static void update_internal(const shared_state& shared, internal_state& internal) {
  }
  static void initial(real_type time, const shared_state& shared, internal_state& internal, rng_state_type& rng_state, real_type* state) {
    for (size_t i = 1; i <= shared.dim.Su.size; ++i) {
      state[i - 1 + 0] = shared.init_state[i - 1];
    }
    for (size_t i = 1; i <= shared.dim.Su.size; ++i) {
      state[i - 1 + shared.odin.offset.state[1]] = shared.init_state[i - 1 + shared.dim.init_state.mult[1]];
    }
    for (size_t i = 1; i <= shared.dim.Su.size; ++i) {
      state[i - 1 + shared.odin.offset.state[2]] = shared.init_state[i - 1 + 2 * shared.dim.init_state.mult[1]];
    }
    for (size_t i = 1; i <= shared.dim.Su.size; ++i) {
      state[i - 1 + shared.odin.offset.state[3]] = shared.init_state[i - 1 + 3 * shared.dim.init_state.mult[1]];
    }
    for (size_t i = 1; i <= shared.dim.Su.size; ++i) {
      state[i - 1 + shared.odin.offset.state[4]] = shared.init_state[i - 1 + 4 * shared.dim.init_state.mult[1]];
    }
    for (size_t i = 1; i <= shared.dim.Su.size; ++i) {
      state[i - 1 + shared.odin.offset.state[5]] = shared.init_state[i - 1 + 5 * shared.dim.init_state.mult[1]];
    }
    for (size_t i = 1; i <= shared.dim.Su.size; ++i) {
      state[i - 1 + shared.odin.offset.state[6]] = shared.init_state[i - 1 + 6 * shared.dim.init_state.mult[1]];
    }
    for (size_t i = 1; i <= shared.dim.Su.size; ++i) {
      state[i - 1 + shared.odin.offset.state[7]] = shared.init_state[i - 1 + 7 * shared.dim.init_state.mult[1]];
    }
    for (size_t i = 1; i <= shared.dim.Su.size; ++i) {
      state[i - 1 + shared.odin.offset.state[8]] = shared.init_state[i - 1 + 8 * shared.dim.init_state.mult[1]];
    }
    for (size_t i = 1; i <= shared.dim.Su.size; ++i) {
      state[i - 1 + shared.odin.offset.state[9]] = shared.init_state[i - 1 + 9 * shared.dim.init_state.mult[1]];
    }
    for (size_t i = 1; i <= shared.dim.Su.size; ++i) {
      state[i - 1 + shared.odin.offset.state[10]] = shared.init_state[i - 1 + 10 * shared.dim.init_state.mult[1]];
    }
    for (size_t i = 1; i <= shared.dim.Su.size; ++i) {
      state[i - 1 + shared.odin.offset.state[11]] = shared.init_state[i - 1 + 11 * shared.dim.init_state.mult[1]];
    }
    for (size_t i = 1; i <= shared.dim.Su.size; ++i) {
      state[i - 1 + shared.odin.offset.state[12]] = 0;
    }
    for (size_t i = 1; i <= shared.dim.Su.size; ++i) {
      state[i - 1 + shared.odin.offset.state[13]] = 0;
    }
    for (size_t i = 1; i <= shared.dim.Su.size; ++i) {
      state[i - 1 + shared.odin.offset.state[14]] = 0;
    }
    for (size_t i = 1; i <= shared.dim.Su.size; ++i) {
      state[i - 1 + shared.odin.offset.state[15]] = 0;
    }
    for (size_t i = 1; i <= shared.dim.Su.size; ++i) {
      state[i - 1 + shared.odin.offset.state[16]] = 0;
    }
    for (size_t i = 1; i <= shared.dim.Su.size; ++i) {
      state[i - 1 + shared.odin.offset.state[17]] = 0;
    }
    for (size_t i = 1; i <= shared.dim.Su.size; ++i) {
      state[i - 1 + shared.odin.offset.state[18]] = 0;
    }
    for (size_t i = 1; i <= shared.dim.Su.size; ++i) {
      state[i - 1 + shared.odin.offset.state[19]] = 0;
    }
    for (size_t i = 1; i <= shared.dim.Su.size; ++i) {
      state[i - 1 + shared.odin.offset.state[20]] = 0;
    }
    for (size_t i = 1; i <= shared.dim.Su.size; ++i) {
      state[i - 1 + shared.odin.offset.state[21]] = 0;
    }
    for (size_t i = 1; i <= shared.dim.Su.size; ++i) {
      state[i - 1 + shared.odin.offset.state[22]] = 0;
    }
    for (size_t i = 1; i <= shared.dim.Su.size; ++i) {
      state[i - 1 + shared.odin.offset.state[23]] = 0;
    }
  }
  static void update(real_type time, real_type dt, const real_type* state, const shared_state& shared, internal_state& internal, rng_state_type& rng_state, real_type* state_next) {
    const auto * Su = state + 0;
    const auto * Eu = state + shared.odin.offset.state[1];
    const auto * Cu = state + shared.odin.offset.state[2];
    const auto * Hu = state + shared.odin.offset.state[3];
    const auto * Ru = state + shared.odin.offset.state[4];
    const auto * Du = state + shared.odin.offset.state[5];
    const auto * Sv = state + shared.odin.offset.state[6];
    const auto * Ev = state + shared.odin.offset.state[7];
    const auto * Cv = state + shared.odin.offset.state[8];
    const auto * Hv = state + shared.odin.offset.state[9];
    const auto * Rv = state + shared.odin.offset.state[10];
    const auto * Dv = state + shared.odin.offset.state[11];
    const auto * Su_i = state + shared.odin.offset.state[12];
    const auto * Eu_i = state + shared.odin.offset.state[13];
    const auto * Cu_i = state + shared.odin.offset.state[14];
    const auto * Hu_i = state + shared.odin.offset.state[15];
    const auto * Ru_i = state + shared.odin.offset.state[16];
    const auto * Du_i = state + shared.odin.offset.state[17];
    const auto * Sv_i = state + shared.odin.offset.state[18];
    const auto * Ev_i = state + shared.odin.offset.state[19];
    const auto * Cv_i = state + shared.odin.offset.state[20];
    const auto * Hv_i = state + shared.odin.offset.state[21];
    const auto * Rv_i = state + shared.odin.offset.state[22];
    const auto * Dv_i = state + shared.odin.offset.state[23];
    for (size_t i = 1; i <= shared.dim.Su.size; ++i) {
      internal.hosp_required[i - 1] = Hu[i - 1] + Hv[i - 1];
    }
    for (size_t i = 1; i <= shared.dim.kappa_E.dim[0]; ++i) {
      for (size_t j = 1; j <= shared.dim.kappa_E.dim[1]; ++j) {
        internal.lambda_Eu[i - 1 + (j - 1) * shared.dim.kappa_E.mult[1]] = shared.kappa_E[i - 1 + (j - 1) * shared.dim.kappa_E.mult[1]] * Eu[j - 1] / shared.N;
      }
    }
    for (size_t i = 1; i <= shared.dim.kappa_E.dim[0]; ++i) {
      for (size_t j = 1; j <= shared.dim.kappa_E.dim[1]; ++j) {
        internal.lambda_Ev[i - 1 + (j - 1) * shared.dim.kappa_E.mult[1]] = (1 - shared.vax_infectiousness) * shared.kappa_E[i - 1 + (j - 1) * shared.dim.kappa_E.mult[1]] * Ev[j - 1] / shared.N;
      }
    }
    for (size_t i = 1; i <= shared.dim.kappa_E.dim[0]; ++i) {
      for (size_t j = 1; j <= shared.dim.kappa_E.dim[1]; ++j) {
        internal.lambda_Cu[i - 1 + (j - 1) * shared.dim.kappa_E.mult[1]] = shared.kappa_C[i - 1 + (j - 1) * shared.dim.kappa_E.mult[1]] * Cu[j - 1] / shared.N;
      }
    }
    for (size_t i = 1; i <= shared.dim.kappa_E.dim[0]; ++i) {
      for (size_t j = 1; j <= shared.dim.kappa_E.dim[1]; ++j) {
        internal.lambda_Cv[i - 1 + (j - 1) * shared.dim.kappa_E.mult[1]] = (1 - shared.vax_infectiousness) * shared.kappa_C[i - 1 + (j - 1) * shared.dim.kappa_E.mult[1]] * Cv[j - 1] / shared.N;
      }
    }
    for (size_t i = 1; i <= shared.dim.kappa_E.dim[0]; ++i) {
      for (size_t j = 1; j <= shared.dim.kappa_E.dim[1]; ++j) {
        internal.lambda_Hu[i - 1 + (j - 1) * shared.dim.kappa_E.mult[1]] = shared.kappa_H[i - 1 + (j - 1) * shared.dim.kappa_E.mult[1]] * Hu[j - 1] / shared.N;
      }
    }
    for (size_t i = 1; i <= shared.dim.kappa_E.dim[0]; ++i) {
      for (size_t j = 1; j <= shared.dim.kappa_E.dim[1]; ++j) {
        internal.lambda_Hv[i - 1 + (j - 1) * shared.dim.kappa_E.mult[1]] = (1 - shared.vax_infectiousness) * shared.kappa_H[i - 1 + (j - 1) * shared.dim.kappa_E.mult[1]] * Hv[j - 1] / shared.N;
      }
    }
    const real_type hosp_required_total = dust2::array::sum<real_type>(internal.hosp_required.data(), shared.dim.Su);
    internal.hosp_rem[0] = shared.hosp_capacity;
    for (size_t i = 2; i <= static_cast<size_t>(shared.n_age); ++i) {
      internal.hosp_rem[i - 1] = monty::math::max<real_type>(0, internal.hosp_rem[i - 1 - 1] - internal.hosp_required[shared.n_age - i + 2 - 1]);
    }
    for (size_t i = 1; i <= shared.dim.Su.size; ++i) {
      internal.lambda_E[i - 1] = dust2::array::sum<real_type>(internal.lambda_Eu.data(), shared.dim.kappa_E, {i - 1, i - 1}, {0, shared.dim.kappa_E.dim[1] - 1}) + dust2::array::sum<real_type>(internal.lambda_Ev.data(), shared.dim.kappa_E, {i - 1, i - 1}, {0, shared.dim.kappa_E.dim[1] - 1});
    }
    for (size_t i = 1; i <= shared.dim.Su.size; ++i) {
      internal.lambda_C[i - 1] = dust2::array::sum<real_type>(internal.lambda_Cu.data(), shared.dim.kappa_E, {i - 1, i - 1}, {0, shared.dim.kappa_E.dim[1] - 1}) + dust2::array::sum<real_type>(internal.lambda_Cv.data(), shared.dim.kappa_E, {i - 1, i - 1}, {0, shared.dim.kappa_E.dim[1] - 1});
    }
    for (size_t i = 1; i <= shared.dim.Su.size; ++i) {
      internal.lambda_H[i - 1] = dust2::array::sum<real_type>(internal.lambda_Hu.data(), shared.dim.kappa_E, {i - 1, i - 1}, {0, shared.dim.kappa_E.dim[1] - 1}) + dust2::array::sum<real_type>(internal.lambda_Hv.data(), shared.dim.kappa_E, {i - 1, i - 1}, {0, shared.dim.kappa_E.dim[1] - 1});
    }
    for (size_t i = 1; i <= shared.dim.Su.size; ++i) {
      internal.hospitalised[i - 1] = ((shared.hosp_prioritised ? (monty::math::min<real_type>(internal.hosp_required[i - 1], internal.hosp_rem[shared.n_age - i + 1 - 1])) : ((hosp_required_total > 0 ? (shared.hosp_capacity * internal.hosp_required[i - 1] / hosp_required_total) : 0))));
    }
    for (size_t i = 1; i <= shared.dim.Su.size; ++i) {
      internal.p_Eu_exit[i - 1] = 1 - monty::math::exp<real_type>(-(shared.sigma_Eu[i - 1] + shared.eta_Eu[i - 1]) * dt);
    }
    for (size_t i = 1; i <= shared.dim.Su.size; ++i) {
      internal.p_Ev_exit[i - 1] = 1 - monty::math::exp<real_type>(-(shared.sigma_Ev[i - 1] + shared.eta_Ev[i - 1]) * dt);
    }
    for (size_t i = 1; i <= shared.dim.Su.size; ++i) {
      internal.p_Cu_exit[i - 1] = 1 - monty::math::exp<real_type>(-(shared.gamma_Cu[i - 1] + shared.mu_Cu[i - 1]) * dt);
    }
    for (size_t i = 1; i <= shared.dim.Su.size; ++i) {
      internal.p_Cv_exit[i - 1] = 1 - monty::math::exp<real_type>(-(shared.gamma_Cv[i - 1] + shared.mu_Cv[i - 1]) * dt);
    }
    for (size_t i = 1; i <= shared.dim.Su.size; ++i) {
      internal.lambda_u[i - 1] = shared.p_trans * (internal.lambda_E[i - 1] + internal.lambda_C[i - 1] + internal.lambda_H[i - 1]);
    }
    for (size_t i = 1; i <= shared.dim.Su.size; ++i) {
      internal.lambda_v[i - 1] = shared.p_trans * (1 - shared.vax_infection) * (internal.lambda_E[i - 1] + internal.lambda_C[i - 1] + internal.lambda_H[i - 1]);
    }
    for (size_t i = 1; i <= shared.dim.Su.size; ++i) {
      internal.total_hosp_mortality[i - 1] = ((internal.hosp_required[i - 1] > 0 ? ((shared.hosp_mortality[i - 1] * internal.hospitalised[i - 1] + shared.unhosp_mortality[i - 1] * (internal.hosp_required[i - 1] - internal.hospitalised[i - 1])) / internal.hosp_required[i - 1]) : shared.hosp_mortality[i - 1]));
    }
    for (size_t i = 1; i <= shared.dim.Su.size; ++i) {
      internal.n_Eu_exit[i - 1] = monty::random::binomial<real_type>(rng_state, Eu[i - 1], internal.p_Eu_exit[i - 1]);
    }
    for (size_t i = 1; i <= shared.dim.Su.size; ++i) {
      internal.n_Ev_exit[i - 1] = monty::random::binomial<real_type>(rng_state, Ev[i - 1], internal.p_Ev_exit[i - 1]);
    }
    for (size_t i = 1; i <= shared.dim.Su.size; ++i) {
      internal.n_Cu_exit[i - 1] = monty::random::binomial<real_type>(rng_state, Cu[i - 1], internal.p_Cu_exit[i - 1]);
    }
    for (size_t i = 1; i <= shared.dim.Su.size; ++i) {
      internal.n_Cv_exit[i - 1] = monty::random::binomial<real_type>(rng_state, Cv[i - 1], internal.p_Cv_exit[i - 1]);
    }
    for (size_t i = 1; i <= shared.dim.Su.size; ++i) {
      internal.gamma_Hu[i - 1] = (1 - internal.total_hosp_mortality[i - 1]) / shared.hosp_duration[i - 1];
    }
    for (size_t i = 1; i <= shared.dim.Su.size; ++i) {
      internal.mu_Hu[i - 1] = internal.total_hosp_mortality[i - 1] / shared.hosp_duration[i - 1];
    }
    for (size_t i = 1; i <= shared.dim.Su.size; ++i) {
      internal.gamma_Hv[i - 1] = (1 - (1 - shared.vax_death) * internal.total_hosp_mortality[i - 1]) / shared.hosp_duration[i - 1];
    }
    for (size_t i = 1; i <= shared.dim.Su.size; ++i) {
      internal.mu_Hv[i - 1] = (1 - shared.vax_death) * internal.total_hosp_mortality[i - 1] / shared.hosp_duration[i - 1];
    }
    for (size_t i = 1; i <= shared.dim.Su.size; ++i) {
      internal.p_Su_to_Eu[i - 1] = monty::math::max<real_type>(0, 1 - monty::math::exp<real_type>(-internal.lambda_u[i - 1] * dt));
    }
    for (size_t i = 1; i <= shared.dim.Su.size; ++i) {
      internal.p_Sv_to_Ev[i - 1] = monty::math::max<real_type>(0, 1 - monty::math::exp<real_type>(-internal.lambda_v[i - 1] * dt));
    }
    for (size_t i = 1; i <= shared.dim.Su.size; ++i) {
      internal.n_Eu_to_Cu[i - 1] = monty::random::binomial<real_type>(rng_state, internal.n_Eu_exit[i - 1], shared.frac_Eu_to_Cu[i - 1]);
    }
    for (size_t i = 1; i <= shared.dim.Su.size; ++i) {
      internal.n_Ev_to_Cv[i - 1] = monty::random::binomial<real_type>(rng_state, internal.n_Ev_exit[i - 1], shared.frac_Ev_to_Cv[i - 1]);
    }
    for (size_t i = 1; i <= shared.dim.Su.size; ++i) {
      internal.n_Cu_to_Ru[i - 1] = monty::random::binomial<real_type>(rng_state, internal.n_Cu_exit[i - 1], shared.frac_Cu_to_R[i - 1]);
    }
    for (size_t i = 1; i <= shared.dim.Su.size; ++i) {
      internal.n_Cv_to_Rv[i - 1] = monty::random::binomial<real_type>(rng_state, internal.n_Cv_exit[i - 1], shared.frac_Cv_to_R[i - 1]);
    }
    for (size_t i = 1; i <= shared.dim.Su.size; ++i) {
      internal.p_Hu_exit[i - 1] = 1 - monty::math::exp<real_type>(-(internal.gamma_Hu[i - 1] + internal.mu_Hu[i - 1]) * dt);
    }
    for (size_t i = 1; i <= shared.dim.Su.size; ++i) {
      internal.p_Hv_exit[i - 1] = 1 - monty::math::exp<real_type>(-(internal.gamma_Hv[i - 1] + internal.mu_Hv[i - 1]) * dt);
    }
    for (size_t i = 1; i <= shared.dim.Su.size; ++i) {
      internal.frac_Hu_to_R[i - 1] = ((internal.gamma_Hu[i - 1] + internal.mu_Hu[i - 1] > 0 ? internal.gamma_Hu[i - 1] / (internal.gamma_Hu[i - 1] + internal.mu_Hu[i - 1]) : 0));
    }
    for (size_t i = 1; i <= shared.dim.Su.size; ++i) {
      internal.frac_Hv_to_R[i - 1] = ((internal.gamma_Hv[i - 1] + internal.mu_Hv[i - 1] > 0 ? internal.gamma_Hv[i - 1] / (internal.gamma_Hv[i - 1] + internal.mu_Hv[i - 1]) : 0));
    }
    for (size_t i = 1; i <= shared.dim.Su.size; ++i) {
      internal.n_Su_to_Eu[i - 1] = monty::random::binomial<real_type>(rng_state, Su[i - 1], internal.p_Su_to_Eu[i - 1]);
    }
    for (size_t i = 1; i <= shared.dim.Su.size; ++i) {
      internal.n_Sv_to_Ev[i - 1] = monty::random::binomial<real_type>(rng_state, Sv[i - 1], internal.p_Sv_to_Ev[i - 1]);
    }
    for (size_t i = 1; i <= shared.dim.Su.size; ++i) {
      internal.n_Eu_to_Hu[i - 1] = internal.n_Eu_exit[i - 1] - internal.n_Eu_to_Cu[i - 1];
    }
    for (size_t i = 1; i <= shared.dim.Su.size; ++i) {
      internal.n_Ev_to_Hv[i - 1] = internal.n_Ev_exit[i - 1] - internal.n_Ev_to_Cv[i - 1];
    }
    for (size_t i = 1; i <= shared.dim.Su.size; ++i) {
      internal.n_Cu_to_Du[i - 1] = internal.n_Cu_exit[i - 1] - internal.n_Cu_to_Ru[i - 1];
    }
    for (size_t i = 1; i <= shared.dim.Su.size; ++i) {
      internal.n_Cv_to_Dv[i - 1] = internal.n_Cv_exit[i - 1] - internal.n_Cv_to_Rv[i - 1];
    }
    for (size_t i = 1; i <= shared.dim.Su.size; ++i) {
      internal.n_Hu_exit[i - 1] = monty::random::binomial<real_type>(rng_state, Hu[i - 1], internal.p_Hu_exit[i - 1]);
    }
    for (size_t i = 1; i <= shared.dim.Su.size; ++i) {
      internal.n_Hv_exit[i - 1] = monty::random::binomial<real_type>(rng_state, Hv[i - 1], internal.p_Hv_exit[i - 1]);
    }
    for (size_t i = 1; i <= shared.dim.Su.size; ++i) {
      internal.Su_after_inf[i - 1] = monty::math::max<real_type>(0, Su[i - 1] - internal.n_Su_to_Eu[i - 1]);
    }
    for (size_t i = 1; i <= shared.dim.Su.size; ++i) {
      internal.n_Hu_to_Ru[i - 1] = monty::random::binomial<real_type>(rng_state, internal.n_Hu_exit[i - 1], internal.frac_Hu_to_R[i - 1]);
    }
    for (size_t i = 1; i <= shared.dim.Su.size; ++i) {
      internal.n_Hv_to_Rv[i - 1] = monty::random::binomial<real_type>(rng_state, internal.n_Hv_exit[i - 1], internal.frac_Hv_to_R[i - 1]);
    }
    const real_type Su_after_inf_total = dust2::array::sum<real_type>(internal.Su_after_inf.data(), shared.dim.Su);
    internal.vax_rem[0] = monty::math::min<real_type>(internal.Su_after_inf[shared.n_age - 1], shared.vax_rate);
    for (size_t i = 2; i <= static_cast<size_t>(shared.n_age); ++i) {
      internal.vax_rem[i - 1] = internal.vax_rem[i - 1 - 1] + monty::math::min<real_type>(internal.Su_after_inf[shared.n_age - i + 1 - 1], shared.vax_rate - internal.vax_rem[i - 1 - 1]);
    }
    for (size_t i = 1; i <= shared.dim.Su.size; ++i) {
      internal.n_Hu_to_Du[i - 1] = internal.n_Hu_exit[i - 1] - internal.n_Hu_to_Ru[i - 1];
    }
    for (size_t i = 1; i <= shared.dim.Su.size; ++i) {
      internal.n_Hv_to_Dv[i - 1] = internal.n_Hv_exit[i - 1] - internal.n_Hv_to_Rv[i - 1];
    }
    for (size_t i = 1; i <= shared.dim.Su.size; ++i) {
      internal.vax_target[i - 1] = ((shared.vax_prioritised ? ((static_cast<int>(i) == shared.n_age ? monty::math::min<real_type>(internal.Su_after_inf[shared.n_age - 1], shared.vax_rate) : monty::math::min<real_type>(internal.Su_after_inf[i - 1], shared.vax_rate - internal.vax_rem[shared.n_age - i - 1]))) : ((Su_after_inf_total > 0 ? shared.vax_rate * internal.Su_after_inf[i - 1] / Su_after_inf_total : 0))));
    }
    for (size_t i = 1; i <= shared.dim.Su.size; ++i) {
      internal.p_Su_to_Sv[i - 1] = monty::math::min<real_type>(1, internal.vax_target[i - 1] / monty::math::max<real_type>(static_cast<real_type>(1e-10), internal.Su_after_inf[i - 1]));
    }
    for (size_t i = 1; i <= shared.dim.Su.size; ++i) {
      internal.n_Su_to_Sv[i - 1] = monty::random::binomial<real_type>(rng_state, internal.Su_after_inf[i - 1], internal.p_Su_to_Sv[i - 1]);
    }
    for (size_t i = 1; i <= shared.dim.Su.size; ++i) {
      state_next[i - 1 + 0] = Su[i - 1] - internal.n_Su_to_Eu[i - 1] - internal.n_Su_to_Sv[i - 1];
    }
    for (size_t i = 1; i <= shared.dim.Su.size; ++i) {
      state_next[i - 1 + shared.odin.offset.state[1]] = Eu[i - 1] + internal.n_Su_to_Eu[i - 1] - internal.n_Eu_exit[i - 1];
    }
    for (size_t i = 1; i <= shared.dim.Su.size; ++i) {
      state_next[i - 1 + shared.odin.offset.state[2]] = Cu[i - 1] + internal.n_Eu_to_Cu[i - 1] - internal.n_Cu_exit[i - 1];
    }
    for (size_t i = 1; i <= shared.dim.Su.size; ++i) {
      state_next[i - 1 + shared.odin.offset.state[3]] = Hu[i - 1] + internal.n_Eu_to_Hu[i - 1] - internal.n_Hu_exit[i - 1];
    }
    for (size_t i = 1; i <= shared.dim.Su.size; ++i) {
      state_next[i - 1 + shared.odin.offset.state[4]] = Ru[i - 1] + internal.n_Cu_to_Ru[i - 1] + internal.n_Hu_to_Ru[i - 1];
    }
    for (size_t i = 1; i <= shared.dim.Su.size; ++i) {
      state_next[i - 1 + shared.odin.offset.state[5]] = Du[i - 1] + internal.n_Cu_to_Du[i - 1] + internal.n_Hu_to_Du[i - 1];
    }
    for (size_t i = 1; i <= shared.dim.Su.size; ++i) {
      state_next[i - 1 + shared.odin.offset.state[6]] = Sv[i - 1] + internal.n_Su_to_Sv[i - 1] - internal.n_Sv_to_Ev[i - 1];
    }
    for (size_t i = 1; i <= shared.dim.Su.size; ++i) {
      state_next[i - 1 + shared.odin.offset.state[7]] = Ev[i - 1] + internal.n_Sv_to_Ev[i - 1] - internal.n_Ev_exit[i - 1];
    }
    for (size_t i = 1; i <= shared.dim.Su.size; ++i) {
      state_next[i - 1 + shared.odin.offset.state[8]] = Cv[i - 1] + internal.n_Ev_to_Cv[i - 1] - internal.n_Cv_exit[i - 1];
    }
    for (size_t i = 1; i <= shared.dim.Su.size; ++i) {
      state_next[i - 1 + shared.odin.offset.state[9]] = Hv[i - 1] + internal.n_Ev_to_Hv[i - 1] - internal.n_Hv_exit[i - 1];
    }
    for (size_t i = 1; i <= shared.dim.Su.size; ++i) {
      state_next[i - 1 + shared.odin.offset.state[10]] = Rv[i - 1] + internal.n_Cv_to_Rv[i - 1] + internal.n_Hv_to_Rv[i - 1];
    }
    for (size_t i = 1; i <= shared.dim.Su.size; ++i) {
      state_next[i - 1 + shared.odin.offset.state[11]] = Dv[i - 1] + internal.n_Cv_to_Dv[i - 1] + internal.n_Hv_to_Dv[i - 1];
    }
    for (size_t i = 1; i <= shared.dim.Su.size; ++i) {
      state_next[i - 1 + shared.odin.offset.state[12]] = Su_i[i - 1];
    }
    for (size_t i = 1; i <= shared.dim.Su.size; ++i) {
      state_next[i - 1 + shared.odin.offset.state[13]] = Eu_i[i - 1] + internal.n_Su_to_Eu[i - 1];
    }
    for (size_t i = 1; i <= shared.dim.Su.size; ++i) {
      state_next[i - 1 + shared.odin.offset.state[14]] = Cu_i[i - 1] + internal.n_Eu_to_Cu[i - 1];
    }
    for (size_t i = 1; i <= shared.dim.Su.size; ++i) {
      state_next[i - 1 + shared.odin.offset.state[15]] = Hu_i[i - 1] + internal.n_Eu_to_Hu[i - 1];
    }
    for (size_t i = 1; i <= shared.dim.Su.size; ++i) {
      state_next[i - 1 + shared.odin.offset.state[16]] = Ru_i[i - 1] + internal.n_Cu_to_Ru[i - 1] + internal.n_Hu_to_Ru[i - 1];
    }
    for (size_t i = 1; i <= shared.dim.Su.size; ++i) {
      state_next[i - 1 + shared.odin.offset.state[17]] = Du_i[i - 1] + internal.n_Cu_to_Du[i - 1] + internal.n_Hu_to_Du[i - 1];
    }
    for (size_t i = 1; i <= shared.dim.Su.size; ++i) {
      state_next[i - 1 + shared.odin.offset.state[18]] = Sv_i[i - 1] + internal.n_Su_to_Sv[i - 1];
    }
    for (size_t i = 1; i <= shared.dim.Su.size; ++i) {
      state_next[i - 1 + shared.odin.offset.state[19]] = Ev_i[i - 1] + internal.n_Sv_to_Ev[i - 1];
    }
    for (size_t i = 1; i <= shared.dim.Su.size; ++i) {
      state_next[i - 1 + shared.odin.offset.state[20]] = Cv_i[i - 1] + internal.n_Ev_to_Cv[i - 1];
    }
    for (size_t i = 1; i <= shared.dim.Su.size; ++i) {
      state_next[i - 1 + shared.odin.offset.state[21]] = Hv_i[i - 1] + internal.n_Ev_to_Hv[i - 1];
    }
    for (size_t i = 1; i <= shared.dim.Su.size; ++i) {
      state_next[i - 1 + shared.odin.offset.state[22]] = Rv_i[i - 1] + internal.n_Cv_to_Rv[i - 1] + internal.n_Hv_to_Rv[i - 1];
    }
    for (size_t i = 1; i <= shared.dim.Su.size; ++i) {
      state_next[i - 1 + shared.odin.offset.state[23]] = Dv_i[i - 1] + internal.n_Cv_to_Dv[i - 1] + internal.n_Hv_to_Dv[i - 1];
    }
  }
  static auto zero_every(const shared_state& shared) {
    return dust2::zero_every_type<real_type>{{1, {dust2::tools::integer_sequence(shared.dim.Su.size, shared.odin.offset.state[12])}}, {1, {dust2::tools::integer_sequence(shared.dim.Su.size, shared.odin.offset.state[13])}}, {1, {dust2::tools::integer_sequence(shared.dim.Su.size, shared.odin.offset.state[14])}}, {1, {dust2::tools::integer_sequence(shared.dim.Su.size, shared.odin.offset.state[15])}}, {1, {dust2::tools::integer_sequence(shared.dim.Su.size, shared.odin.offset.state[16])}}, {1, {dust2::tools::integer_sequence(shared.dim.Su.size, shared.odin.offset.state[17])}}, {1, {dust2::tools::integer_sequence(shared.dim.Su.size, shared.odin.offset.state[18])}}, {1, {dust2::tools::integer_sequence(shared.dim.Su.size, shared.odin.offset.state[19])}}, {1, {dust2::tools::integer_sequence(shared.dim.Su.size, shared.odin.offset.state[20])}}, {1, {dust2::tools::integer_sequence(shared.dim.Su.size, shared.odin.offset.state[21])}}, {1, {dust2::tools::integer_sequence(shared.dim.Su.size, shared.odin.offset.state[22])}}, {1, {dust2::tools::integer_sequence(shared.dim.Su.size, shared.odin.offset.state[23])}}};
  }
  static real_type compare_data(real_type time, const real_type* state, const data_type& data, const shared_state& shared, internal_state& internal, rng_state_type& rng_state) {
    auto unless_nan = [](real_type x) { return std::isnan(x) ? 0 : x; };
    const auto * Eu_i = state + shared.odin.offset.state[13];
    const auto * Ev_i = state + shared.odin.offset.state[19];
    real_type odin_ll = 0;
    for (size_t i = 1; i <= shared.dim.Su.size; ++i) {
      odin_ll += unless_nan(monty::density::poisson(data.E_reported[i - 1], Eu_i[i - 1] + Ev_i[i - 1] + static_cast<real_type>(0.10000000000000001), true));
    }
    return odin_ll;
  }
};

#include <cpp11.hpp>
#include <dust2/r/discrete/system.hpp>
#include <dust2/r/discrete/filter.hpp>
#include <dust2/r/discrete/unfilter.hpp>

[[cpp11::register]]
SEXP dust2_system_simex_alloc(cpp11::list r_pars, cpp11::sexp r_time, cpp11::list r_time_control, cpp11::sexp r_n_particles, cpp11::sexp r_n_groups, cpp11::sexp r_seed, cpp11::sexp r_deterministic, cpp11::sexp r_n_threads) {
  return dust2::r::dust2_discrete_alloc<simex>(r_pars, r_time, r_time_control, r_n_particles, r_n_groups, r_seed, r_deterministic, r_n_threads);
}
[[cpp11::register]]
SEXP dust2_system_simex_run_to_time(cpp11::sexp ptr, cpp11::sexp r_time) {
  return dust2::r::dust2_system_run_to_time<dust2::dust_discrete<simex>>(ptr, r_time);
}

[[cpp11::register]]
SEXP dust2_system_simex_state(cpp11::sexp ptr, cpp11::sexp r_index_state, cpp11::sexp r_index_particle, cpp11::sexp r_index_group, bool preserve_particle_dimension, bool preserve_group_dimension) {
  return dust2::r::dust2_system_state<dust2::dust_discrete<simex>>(ptr, r_index_state, r_index_particle, r_index_group, preserve_particle_dimension, preserve_group_dimension);
}

[[cpp11::register]]
SEXP dust2_system_simex_time(cpp11::sexp ptr) {
  return dust2::r::dust2_system_time<dust2::dust_discrete<simex>>(ptr);
}

[[cpp11::register]]
SEXP dust2_system_simex_set_state_initial(cpp11::sexp ptr) {
  return dust2::r::dust2_system_set_state_initial<dust2::dust_discrete<simex>>(ptr);
}

[[cpp11::register]]
SEXP dust2_system_simex_set_state(cpp11::sexp ptr, cpp11::list r_state) {
  return dust2::r::dust2_system_set_state<dust2::dust_discrete<simex>>(ptr, r_state);
}

[[cpp11::register]]
SEXP dust2_system_simex_reorder(cpp11::sexp ptr, cpp11::integers r_index) {
  return dust2::r::dust2_system_reorder<dust2::dust_discrete<simex>>(ptr, r_index);
}

[[cpp11::register]]
SEXP dust2_system_simex_rng_state(cpp11::sexp ptr) {
  return dust2::r::dust2_system_rng_state<dust2::dust_discrete<simex>>(ptr);
}

[[cpp11::register]]
SEXP dust2_system_simex_set_rng_state(cpp11::sexp ptr, cpp11::sexp r_rng_state) {
  return dust2::r::dust2_system_set_rng_state<dust2::dust_discrete<simex>>(ptr, r_rng_state);
}

[[cpp11::register]]
SEXP dust2_system_simex_set_time(cpp11::sexp ptr, cpp11::sexp r_time) {
  return dust2::r::dust2_system_set_time<dust2::dust_discrete<simex>>(ptr, r_time);
}

[[cpp11::register]]
SEXP dust2_system_simex_update_pars(cpp11::sexp ptr, cpp11::list pars) {
  return dust2::r::dust2_system_update_pars<dust2::dust_discrete<simex>>(ptr, pars);
}

[[cpp11::register]]
SEXP dust2_system_simex_simulate(cpp11::sexp ptr, cpp11::sexp r_times, cpp11::sexp r_index_state, bool preserve_particle_dimension, bool preserve_group_dimension) {
  return dust2::r::dust2_system_simulate<dust2::dust_discrete<simex>>(ptr, r_times, r_index_state, preserve_particle_dimension, preserve_group_dimension);
}

[[cpp11::register]]
SEXP dust2_unfilter_simex_alloc(cpp11::list r_pars, cpp11::sexp r_time_start, cpp11::sexp r_time, cpp11::list r_time_control, cpp11::list r_data, cpp11::sexp r_n_particles, cpp11::sexp r_n_groups, cpp11::sexp r_n_threads) {
  return dust2::r::dust2_discrete_unfilter_alloc<simex>(r_pars, r_time_start, r_time, r_time_control, r_data, r_n_particles, r_n_groups, r_n_threads);
}

[[cpp11::register]]
SEXP dust2_filter_simex_alloc(cpp11::list r_pars, cpp11::sexp r_time_start, cpp11::sexp r_time, cpp11::list r_time_control, cpp11::list r_data, cpp11::sexp r_n_particles, cpp11::sexp r_n_groups, cpp11::sexp r_n_threads, cpp11::sexp r_seed) {
  return dust2::r::dust2_discrete_filter_alloc<simex>(r_pars, r_time_start, r_time, r_time_control, r_data, r_n_particles, r_n_groups, r_n_threads, r_seed);
}
[[cpp11::register]]
SEXP dust2_system_simex_compare_data(cpp11::sexp ptr, cpp11::list r_data, bool preserve_particle_dimension, bool preserve_group_dimension) {
  return dust2::r::dust2_system_compare_data<dust2::dust_discrete<simex>>(ptr, r_data, preserve_particle_dimension, preserve_group_dimension);
}

[[cpp11::register]]
SEXP dust2_unfilter_simex_update_pars(cpp11::sexp ptr, cpp11::list r_pars, cpp11::sexp r_index_group) {
  return dust2::r::dust2_unfilter_update_pars<dust2::dust_discrete<simex>>(ptr, r_pars, r_index_group);
}

[[cpp11::register]]
SEXP dust2_unfilter_simex_run(cpp11::sexp ptr, cpp11::sexp r_initial, bool save_trajectories, cpp11::sexp save_snapshots, bool adjoint, cpp11::sexp r_index_state, cpp11::sexp r_index_group, bool preserve_particle_dimension, bool preserve_group_dimension) {
  return dust2::r::dust2_unfilter_run<dust2::dust_discrete<simex>>(ptr, r_initial, save_trajectories, save_snapshots, adjoint, r_index_state, r_index_group, preserve_particle_dimension, preserve_group_dimension);
}

[[cpp11::register]]
SEXP dust2_unfilter_simex_last_trajectories(cpp11::sexp ptr, bool select_random_particle, bool preserve_particle_dimension, bool preserve_group_dimension) {
  return dust2::r::dust2_unfilter_last_trajectories<dust2::dust_discrete<simex>>(ptr, select_random_particle, preserve_particle_dimension, preserve_group_dimension);
}

[[cpp11::register]]
SEXP dust2_unfilter_simex_last_snapshots(cpp11::sexp ptr, bool select_random_particle, bool preserve_particle_dimension, bool preserve_group_dimension) {
  return dust2::r::dust2_unfilter_last_snapshots<dust2::dust_discrete<simex>>(ptr, select_random_particle, preserve_particle_dimension, preserve_group_dimension);
}

[[cpp11::register]]
SEXP dust2_unfilter_simex_last_state(cpp11::sexp ptr, bool select_random_particle, bool preserve_particle_dimension, bool preserve_group_dimension) {
  return dust2::r::dust2_unfilter_last_state<dust2::dust_discrete<simex>>(ptr, select_random_particle, preserve_particle_dimension, preserve_group_dimension);
}

[[cpp11::register]]
SEXP dust2_filter_simex_update_pars(cpp11::sexp ptr, cpp11::list r_pars, cpp11::sexp r_index_group) {
  return dust2::r::dust2_filter_update_pars<dust2::dust_discrete<simex>>(ptr, r_pars, r_index_group);
}

[[cpp11::register]]
SEXP dust2_filter_simex_run(cpp11::sexp ptr, cpp11::sexp r_initial, bool save_trajectories, cpp11::sexp save_snapshots, bool adjoint, cpp11::sexp index_state, cpp11::sexp index_group, bool preserve_particle_dimension, bool preserve_group_dimension) {
  return dust2::r::dust2_filter_run<dust2::dust_discrete<simex>>(ptr, r_initial, save_trajectories, save_snapshots, adjoint, index_state, index_group, preserve_particle_dimension, preserve_group_dimension);
}

[[cpp11::register]]
SEXP dust2_filter_simex_last_trajectories(cpp11::sexp ptr, bool select_random_particle, bool preserve_particle_dimension, bool preserve_group_dimension) {
  return dust2::r::dust2_filter_last_trajectories<dust2::dust_discrete<simex>>(ptr, select_random_particle, preserve_particle_dimension, preserve_group_dimension);
}

[[cpp11::register]]
SEXP dust2_filter_simex_last_snapshots(cpp11::sexp ptr, bool select_random_particle, bool preserve_particle_dimension, bool preserve_group_dimension) {
  return dust2::r::dust2_filter_last_snapshots<dust2::dust_discrete<simex>>(ptr, select_random_particle, preserve_particle_dimension, preserve_group_dimension);
}

[[cpp11::register]]
SEXP dust2_filter_simex_last_state(cpp11::sexp ptr, bool select_random_particle, bool preserve_particle_dimension, bool preserve_group_dimension) {
  return dust2::r::dust2_filter_last_state<dust2::dust_discrete<simex>>(ptr, select_random_particle, preserve_particle_dimension, preserve_group_dimension);
}

[[cpp11::register]]
SEXP dust2_filter_simex_rng_state(cpp11::sexp ptr) {
  return dust2::r::dust2_filter_rng_state<dust2::dust_discrete<simex>>(ptr);
}

[[cpp11::register]]
SEXP dust2_filter_simex_set_rng_state(cpp11::sexp ptr, cpp11::sexp r_rng_state) {
  return dust2::r::dust2_filter_set_rng_state<dust2::dust_discrete<simex>>(ptr, r_rng_state);
}
