// Generated by dust2 (version 0.3.28) - do not edit

// Generated by odin2 (version 0.3.43) - do not edit
#include <dust2/common.hpp>
// [[dust2::class(tst)]]
// [[dust2::time_type(discrete)]]
// [[dust2::has_compare()]]
// [[dust2::parameter(m, type = "real_type", rank = 2, required = TRUE, constant = FALSE)]]
// [[dust2::parameter(S0, type = "real_type", rank = 1, required = TRUE, constant = FALSE)]]
// [[dust2::parameter(I0, type = "real_type", rank = 1, required = TRUE, constant = FALSE)]]
// [[dust2::parameter(beta, type = "real_type", rank = 0, required = FALSE, constant = FALSE)]]
// [[dust2::parameter(gamma, type = "real_type", rank = 0, required = FALSE, constant = FALSE)]]
// [[dust2::parameter(n_age, type = "int", rank = 0, required = TRUE, constant = TRUE)]]
class tst {
public:
  tst() = delete;
  using real_type = double;
  using rng_state_type = monty::random::generator<real_type>;
  struct shared_state {
    struct odin_internals_type {
      struct {
        dust2::packing state;
      } packing;
      struct {
        std::array<size_t, 4> state;
      } offset;
    } odin;
    struct dim_type {
      dust2::array::dimensions<1> S;
      dust2::array::dimensions<1> I;
      dust2::array::dimensions<1> R;
      dust2::array::dimensions<1> incidence;
      dust2::array::dimensions<2> m;
      dust2::array::dimensions<1> lambda;
      dust2::array::dimensions<1> cases;
    } dim;
    real_type beta;
    real_type gamma;
    int n_age;
    std::vector<real_type> m;
    std::vector<real_type> S0;
    std::vector<real_type> I0;
  };
  struct internal_state {
    std::vector<real_type> n_IR;
    std::vector<real_type> s_ij;
    std::vector<real_type> lambda;
    std::vector<real_type> p_SI;
    std::vector<real_type> n_SI;
  };
  struct data_type {
    std::vector<real_type> cases;
  };
  static dust2::packing packing_state(const shared_state& shared) {
    return shared.odin.packing.state;
  }
  static shared_state build_shared(cpp11::list parameters) {
    shared_state::dim_type dim;
    const real_type beta = dust2::r::read_real(parameters, "beta", static_cast<real_type>(0.016500000000000001));
    const real_type gamma = dust2::r::read_real(parameters, "gamma", static_cast<real_type>(0.10000000000000001));
    const int n_age = dust2::r::read_int(parameters, "n_age");
    dim.S.set({static_cast<size_t>(n_age)});
    dim.I.set({static_cast<size_t>(n_age)});
    dim.R.set({static_cast<size_t>(n_age)});
    dim.incidence.set({static_cast<size_t>(n_age)});
    dim.m.set({static_cast<size_t>(n_age), static_cast<size_t>(n_age)});
    dim.lambda.set({static_cast<size_t>(n_age)});
    dim.cases.set({static_cast<size_t>(n_age)});
    std::vector<real_type> m(dim.m.size);
    dust2::r::read_real_array(parameters, dim.m, m.data(), "m", true);
    std::vector<real_type> S0(dim.S.size);
    dust2::r::read_real_array(parameters, dim.S, S0.data(), "S0", true);
    std::vector<real_type> I0(dim.I.size);
    dust2::r::read_real_array(parameters, dim.I, I0.data(), "I0", true);
    shared_state::odin_internals_type odin;
    odin.packing.state = dust2::packing{
      {"S", std::vector<size_t>(dim.S.dim.begin(), dim.S.dim.end())},
      {"I", std::vector<size_t>(dim.I.dim.begin(), dim.I.dim.end())},
      {"R", std::vector<size_t>(dim.R.dim.begin(), dim.R.dim.end())},
      {"incidence", std::vector<size_t>(dim.incidence.dim.begin(), dim.incidence.dim.end())}
    };
    odin.packing.state.copy_offset(odin.offset.state.begin());
    return shared_state{odin, dim, beta, gamma, n_age, m, S0, I0};
  }
  static internal_state build_internal(const shared_state& shared) {
    std::vector<real_type> n_IR(shared.dim.I.size);
    std::vector<real_type> s_ij(shared.dim.m.size);
    std::vector<real_type> lambda(shared.dim.lambda.size);
    std::vector<real_type> p_SI(shared.dim.S.size);
    std::vector<real_type> n_SI(shared.dim.S.size);
    return internal_state{n_IR, s_ij, lambda, p_SI, n_SI};
  }
  static data_type build_data(cpp11::list data, const shared_state& shared) {
    auto cases = std::vector<real_type>(shared.dim.cases.size);
    dust2::r::read_real_array(data, shared.dim.cases, cases.data(), "cases", true);
    return data_type{cases};
  }
  static void update_shared(cpp11::list parameters, shared_state& shared) {
    shared.beta = dust2::r::read_real(parameters, "beta", shared.beta);
    shared.gamma = dust2::r::read_real(parameters, "gamma", shared.gamma);
    dust2::r::read_real_array(parameters, shared.dim.m, shared.m.data(), "m", false);
    dust2::r::read_real_array(parameters, shared.dim.S, shared.S0.data(), "S0", false);
    dust2::r::read_real_array(parameters, shared.dim.I, shared.I0.data(), "I0", false);
  }
  static void update_internal(const shared_state& shared, internal_state& internal) {
  }
  static void initial(real_type time, const shared_state& shared, internal_state& internal, rng_state_type& rng_state, real_type* state) {
    for (size_t i = 1; i <= shared.dim.S.size; ++i) {
      state[i - 1 + 0] = shared.S0[i - 1];
    }
    for (size_t i = 1; i <= shared.dim.I.size; ++i) {
      state[i - 1 + shared.odin.offset.state[1]] = shared.I0[i - 1];
    }
    for (size_t i = 1; i <= shared.dim.R.size; ++i) {
      state[i - 1 + shared.odin.offset.state[2]] = 0;
    }
    for (size_t i = 1; i <= shared.dim.incidence.size; ++i) {
      state[i - 1 + shared.odin.offset.state[3]] = 0;
    }
  }
  static void update(real_type time, real_type dt, const real_type* state, const shared_state& shared, internal_state& internal, rng_state_type& rng_state, real_type* state_next) {
    const auto * S = state + 0;
    const auto * I = state + shared.odin.offset.state[1];
    const auto * R = state + shared.odin.offset.state[2];
    const auto * incidence = state + shared.odin.offset.state[3];
    const real_type p_IR = 1 - monty::math::exp<real_type>(-shared.gamma * dt);
    for (size_t i = 1; i <= shared.dim.I.size; ++i) {
      internal.n_IR[i - 1] = monty::random::binomial<real_type>(rng_state, I[i - 1], p_IR);
    }
    for (size_t i = 1; i <= shared.dim.m.dim[0]; ++i) {
      for (size_t j = 1; j <= shared.dim.m.dim[1]; ++j) {
        internal.s_ij[i - 1 + (j - 1) * shared.dim.m.mult[1]] = shared.m[i - 1 + (j - 1) * shared.dim.m.mult[1]] * I[j - 1];
      }
    }
    for (size_t i = 1; i <= shared.dim.lambda.size; ++i) {
      internal.lambda[i - 1] = shared.beta * dust2::array::sum<real_type>(internal.s_ij.data(), shared.dim.m, {i - 1, i - 1}, {0, shared.dim.m.dim[1] - 1});
    }
    for (size_t i = 1; i <= shared.dim.S.size; ++i) {
      internal.p_SI[i - 1] = 1 - monty::math::exp<real_type>(-internal.lambda[i - 1] * dt);
    }
    for (size_t i = 1; i <= shared.dim.S.size; ++i) {
      internal.n_SI[i - 1] = monty::random::binomial<real_type>(rng_state, S[i - 1], internal.p_SI[i - 1]);
    }
    for (size_t i = 1; i <= shared.dim.S.size; ++i) {
      state_next[i - 1 + 0] = S[i - 1] - internal.n_SI[i - 1];
    }
    for (size_t i = 1; i <= shared.dim.I.size; ++i) {
      state_next[i - 1 + shared.odin.offset.state[1]] = I[i - 1] + internal.n_SI[i - 1] - internal.n_IR[i - 1];
    }
    for (size_t i = 1; i <= shared.dim.R.size; ++i) {
      state_next[i - 1 + shared.odin.offset.state[2]] = R[i - 1] + internal.n_IR[i - 1];
    }
    for (size_t i = 1; i <= shared.dim.incidence.size; ++i) {
      state_next[i - 1 + shared.odin.offset.state[3]] = incidence[i - 1] + dust2::array::sum<real_type>(internal.n_SI.data(), shared.dim.S);
    }
  }
  static auto zero_every(const shared_state& shared) {
    return dust2::zero_every_type<real_type>{{1, {dust2::tools::integer_sequence(shared.dim.incidence.size, shared.odin.offset.state[3])}}};
  }
  static real_type compare_data(real_type time, const real_type* state, const data_type& data, const shared_state& shared, internal_state& internal, rng_state_type& rng_state) {
    auto unless_nan = [](real_type x) { return std::isnan(x) ? 0 : x; };
    const auto * incidence = state + shared.odin.offset.state[3];
    real_type odin_ll = 0;
    for (size_t i = 1; i <= shared.dim.cases.size; ++i) {
      odin_ll += unless_nan(monty::density::poisson(data.cases[i - 1], incidence[i - 1], true));
    }
    return odin_ll;
  }
};

#include <cpp11.hpp>
#include <dust2/r/discrete/system.hpp>
#include <dust2/r/discrete/filter.hpp>
#include <dust2/r/discrete/unfilter.hpp>

[[cpp11::register]]
SEXP dust2_system_tst_alloc(cpp11::list r_pars, cpp11::sexp r_time, cpp11::list r_time_control, cpp11::sexp r_n_particles, cpp11::sexp r_n_groups, cpp11::sexp r_seed, cpp11::sexp r_deterministic, cpp11::sexp r_n_threads) {
  return dust2::r::dust2_discrete_alloc<tst>(r_pars, r_time, r_time_control, r_n_particles, r_n_groups, r_seed, r_deterministic, r_n_threads);
}
[[cpp11::register]]
SEXP dust2_system_tst_run_to_time(cpp11::sexp ptr, cpp11::sexp r_time) {
  return dust2::r::dust2_system_run_to_time<dust2::dust_discrete<tst>>(ptr, r_time);
}

[[cpp11::register]]
SEXP dust2_system_tst_state(cpp11::sexp ptr, cpp11::sexp r_index_state, cpp11::sexp r_index_particle, cpp11::sexp r_index_group, bool preserve_particle_dimension, bool preserve_group_dimension) {
  return dust2::r::dust2_system_state<dust2::dust_discrete<tst>>(ptr, r_index_state, r_index_particle, r_index_group, preserve_particle_dimension, preserve_group_dimension);
}

[[cpp11::register]]
SEXP dust2_system_tst_time(cpp11::sexp ptr) {
  return dust2::r::dust2_system_time<dust2::dust_discrete<tst>>(ptr);
}

[[cpp11::register]]
SEXP dust2_system_tst_set_state_initial(cpp11::sexp ptr) {
  return dust2::r::dust2_system_set_state_initial<dust2::dust_discrete<tst>>(ptr);
}

[[cpp11::register]]
SEXP dust2_system_tst_set_state(cpp11::sexp ptr, cpp11::list r_state) {
  return dust2::r::dust2_system_set_state<dust2::dust_discrete<tst>>(ptr, r_state);
}

[[cpp11::register]]
SEXP dust2_system_tst_reorder(cpp11::sexp ptr, cpp11::integers r_index) {
  return dust2::r::dust2_system_reorder<dust2::dust_discrete<tst>>(ptr, r_index);
}

[[cpp11::register]]
SEXP dust2_system_tst_rng_state(cpp11::sexp ptr) {
  return dust2::r::dust2_system_rng_state<dust2::dust_discrete<tst>>(ptr);
}

[[cpp11::register]]
SEXP dust2_system_tst_set_rng_state(cpp11::sexp ptr, cpp11::sexp r_rng_state) {
  return dust2::r::dust2_system_set_rng_state<dust2::dust_discrete<tst>>(ptr, r_rng_state);
}

[[cpp11::register]]
SEXP dust2_system_tst_set_time(cpp11::sexp ptr, cpp11::sexp r_time) {
  return dust2::r::dust2_system_set_time<dust2::dust_discrete<tst>>(ptr, r_time);
}

[[cpp11::register]]
SEXP dust2_system_tst_update_pars(cpp11::sexp ptr, cpp11::list pars) {
  return dust2::r::dust2_system_update_pars<dust2::dust_discrete<tst>>(ptr, pars);
}

[[cpp11::register]]
SEXP dust2_system_tst_simulate(cpp11::sexp ptr, cpp11::sexp r_times, cpp11::sexp r_index_state, bool preserve_particle_dimension, bool preserve_group_dimension) {
  return dust2::r::dust2_system_simulate<dust2::dust_discrete<tst>>(ptr, r_times, r_index_state, preserve_particle_dimension, preserve_group_dimension);
}

[[cpp11::register]]
SEXP dust2_unfilter_tst_alloc(cpp11::list r_pars, cpp11::sexp r_time_start, cpp11::sexp r_time, cpp11::list r_time_control, cpp11::list r_data, cpp11::sexp r_n_particles, cpp11::sexp r_n_groups, cpp11::sexp r_n_threads) {
  return dust2::r::dust2_discrete_unfilter_alloc<tst>(r_pars, r_time_start, r_time, r_time_control, r_data, r_n_particles, r_n_groups, r_n_threads);
}

[[cpp11::register]]
SEXP dust2_filter_tst_alloc(cpp11::list r_pars, cpp11::sexp r_time_start, cpp11::sexp r_time, cpp11::list r_time_control, cpp11::list r_data, cpp11::sexp r_n_particles, cpp11::sexp r_n_groups, cpp11::sexp r_n_threads, cpp11::sexp r_seed) {
  return dust2::r::dust2_discrete_filter_alloc<tst>(r_pars, r_time_start, r_time, r_time_control, r_data, r_n_particles, r_n_groups, r_n_threads, r_seed);
}
[[cpp11::register]]
SEXP dust2_system_tst_compare_data(cpp11::sexp ptr, cpp11::list r_data, bool preserve_particle_dimension, bool preserve_group_dimension) {
  return dust2::r::dust2_system_compare_data<dust2::dust_discrete<tst>>(ptr, r_data, preserve_particle_dimension, preserve_group_dimension);
}

[[cpp11::register]]
SEXP dust2_unfilter_tst_update_pars(cpp11::sexp ptr, cpp11::list r_pars, cpp11::sexp r_index_group) {
  return dust2::r::dust2_unfilter_update_pars<dust2::dust_discrete<tst>>(ptr, r_pars, r_index_group);
}

[[cpp11::register]]
SEXP dust2_unfilter_tst_run(cpp11::sexp ptr, cpp11::sexp r_initial, bool save_trajectories, cpp11::sexp save_snapshots, bool adjoint, cpp11::sexp r_index_state, cpp11::sexp r_index_group, bool preserve_particle_dimension, bool preserve_group_dimension) {
  return dust2::r::dust2_unfilter_run<dust2::dust_discrete<tst>>(ptr, r_initial, save_trajectories, save_snapshots, adjoint, r_index_state, r_index_group, preserve_particle_dimension, preserve_group_dimension);
}

[[cpp11::register]]
SEXP dust2_unfilter_tst_last_trajectories(cpp11::sexp ptr, bool select_random_particle, bool preserve_particle_dimension, bool preserve_group_dimension) {
  return dust2::r::dust2_unfilter_last_trajectories<dust2::dust_discrete<tst>>(ptr, select_random_particle, preserve_particle_dimension, preserve_group_dimension);
}

[[cpp11::register]]
SEXP dust2_unfilter_tst_last_snapshots(cpp11::sexp ptr, bool select_random_particle, bool preserve_particle_dimension, bool preserve_group_dimension) {
  return dust2::r::dust2_unfilter_last_snapshots<dust2::dust_discrete<tst>>(ptr, select_random_particle, preserve_particle_dimension, preserve_group_dimension);
}

[[cpp11::register]]
SEXP dust2_unfilter_tst_last_state(cpp11::sexp ptr, bool select_random_particle, bool preserve_particle_dimension, bool preserve_group_dimension) {
  return dust2::r::dust2_unfilter_last_state<dust2::dust_discrete<tst>>(ptr, select_random_particle, preserve_particle_dimension, preserve_group_dimension);
}

[[cpp11::register]]
SEXP dust2_filter_tst_update_pars(cpp11::sexp ptr, cpp11::list r_pars, cpp11::sexp r_index_group) {
  return dust2::r::dust2_filter_update_pars<dust2::dust_discrete<tst>>(ptr, r_pars, r_index_group);
}

[[cpp11::register]]
SEXP dust2_filter_tst_run(cpp11::sexp ptr, cpp11::sexp r_initial, bool save_trajectories, cpp11::sexp save_snapshots, bool adjoint, cpp11::sexp index_state, cpp11::sexp index_group, bool preserve_particle_dimension, bool preserve_group_dimension) {
  return dust2::r::dust2_filter_run<dust2::dust_discrete<tst>>(ptr, r_initial, save_trajectories, save_snapshots, adjoint, index_state, index_group, preserve_particle_dimension, preserve_group_dimension);
}

[[cpp11::register]]
SEXP dust2_filter_tst_last_trajectories(cpp11::sexp ptr, bool select_random_particle, bool preserve_particle_dimension, bool preserve_group_dimension) {
  return dust2::r::dust2_filter_last_trajectories<dust2::dust_discrete<tst>>(ptr, select_random_particle, preserve_particle_dimension, preserve_group_dimension);
}

[[cpp11::register]]
SEXP dust2_filter_tst_last_snapshots(cpp11::sexp ptr, bool select_random_particle, bool preserve_particle_dimension, bool preserve_group_dimension) {
  return dust2::r::dust2_filter_last_snapshots<dust2::dust_discrete<tst>>(ptr, select_random_particle, preserve_particle_dimension, preserve_group_dimension);
}

[[cpp11::register]]
SEXP dust2_filter_tst_last_state(cpp11::sexp ptr, bool select_random_particle, bool preserve_particle_dimension, bool preserve_group_dimension) {
  return dust2::r::dust2_filter_last_state<dust2::dust_discrete<tst>>(ptr, select_random_particle, preserve_particle_dimension, preserve_group_dimension);
}

[[cpp11::register]]
SEXP dust2_filter_tst_rng_state(cpp11::sexp ptr) {
  return dust2::r::dust2_filter_rng_state<dust2::dust_discrete<tst>>(ptr);
}

[[cpp11::register]]
SEXP dust2_filter_tst_set_rng_state(cpp11::sexp ptr, cpp11::sexp r_rng_state) {
  return dust2::r::dust2_filter_set_rng_state<dust2::dust_discrete<tst>>(ptr, r_rng_state);
}
