# Generated by cpp11: do not edit by hand

dust2_system_simex_alloc <- function(r_pars, r_time, r_time_control, r_n_particles, r_n_groups, r_seed, r_deterministic, r_n_threads) {
  .Call(`_simex_dust2_system_simex_alloc`, r_pars, r_time, r_time_control, r_n_particles, r_n_groups, r_seed, r_deterministic, r_n_threads)
}

dust2_system_simex_run_to_time <- function(ptr, r_time) {
  .Call(`_simex_dust2_system_simex_run_to_time`, ptr, r_time)
}

dust2_system_simex_state <- function(ptr, r_index_state, r_index_particle, r_index_group, preserve_particle_dimension, preserve_group_dimension) {
  .Call(`_simex_dust2_system_simex_state`, ptr, r_index_state, r_index_particle, r_index_group, preserve_particle_dimension, preserve_group_dimension)
}

dust2_system_simex_time <- function(ptr) {
  .Call(`_simex_dust2_system_simex_time`, ptr)
}

dust2_system_simex_set_state_initial <- function(ptr) {
  .Call(`_simex_dust2_system_simex_set_state_initial`, ptr)
}

dust2_system_simex_set_state <- function(ptr, r_state) {
  .Call(`_simex_dust2_system_simex_set_state`, ptr, r_state)
}

dust2_system_simex_reorder <- function(ptr, r_index) {
  .Call(`_simex_dust2_system_simex_reorder`, ptr, r_index)
}

dust2_system_simex_rng_state <- function(ptr) {
  .Call(`_simex_dust2_system_simex_rng_state`, ptr)
}

dust2_system_simex_set_rng_state <- function(ptr, r_rng_state) {
  .Call(`_simex_dust2_system_simex_set_rng_state`, ptr, r_rng_state)
}

dust2_system_simex_set_time <- function(ptr, r_time) {
  .Call(`_simex_dust2_system_simex_set_time`, ptr, r_time)
}

dust2_system_simex_update_pars <- function(ptr, pars) {
  .Call(`_simex_dust2_system_simex_update_pars`, ptr, pars)
}

dust2_system_simex_simulate <- function(ptr, r_times, r_index_state, preserve_particle_dimension, preserve_group_dimension) {
  .Call(`_simex_dust2_system_simex_simulate`, ptr, r_times, r_index_state, preserve_particle_dimension, preserve_group_dimension)
}

dust2_unfilter_simex_alloc <- function(r_pars, r_time_start, r_time, r_time_control, r_data, r_n_particles, r_n_groups, r_n_threads) {
  .Call(`_simex_dust2_unfilter_simex_alloc`, r_pars, r_time_start, r_time, r_time_control, r_data, r_n_particles, r_n_groups, r_n_threads)
}

dust2_filter_simex_alloc <- function(r_pars, r_time_start, r_time, r_time_control, r_data, r_n_particles, r_n_groups, r_n_threads, r_seed) {
  .Call(`_simex_dust2_filter_simex_alloc`, r_pars, r_time_start, r_time, r_time_control, r_data, r_n_particles, r_n_groups, r_n_threads, r_seed)
}

dust2_system_simex_compare_data <- function(ptr, r_data, preserve_particle_dimension, preserve_group_dimension) {
  .Call(`_simex_dust2_system_simex_compare_data`, ptr, r_data, preserve_particle_dimension, preserve_group_dimension)
}

dust2_unfilter_simex_update_pars <- function(ptr, r_pars, r_index_group) {
  .Call(`_simex_dust2_unfilter_simex_update_pars`, ptr, r_pars, r_index_group)
}

dust2_unfilter_simex_run <- function(ptr, r_initial, save_trajectories, save_snapshots, adjoint, r_index_state, r_index_group, preserve_particle_dimension, preserve_group_dimension) {
  .Call(`_simex_dust2_unfilter_simex_run`, ptr, r_initial, save_trajectories, save_snapshots, adjoint, r_index_state, r_index_group, preserve_particle_dimension, preserve_group_dimension)
}

dust2_unfilter_simex_last_trajectories <- function(ptr, select_random_particle, preserve_particle_dimension, preserve_group_dimension) {
  .Call(`_simex_dust2_unfilter_simex_last_trajectories`, ptr, select_random_particle, preserve_particle_dimension, preserve_group_dimension)
}

dust2_unfilter_simex_last_snapshots <- function(ptr, select_random_particle, preserve_particle_dimension, preserve_group_dimension) {
  .Call(`_simex_dust2_unfilter_simex_last_snapshots`, ptr, select_random_particle, preserve_particle_dimension, preserve_group_dimension)
}

dust2_unfilter_simex_last_state <- function(ptr, select_random_particle, preserve_particle_dimension, preserve_group_dimension) {
  .Call(`_simex_dust2_unfilter_simex_last_state`, ptr, select_random_particle, preserve_particle_dimension, preserve_group_dimension)
}

dust2_filter_simex_update_pars <- function(ptr, r_pars, r_index_group) {
  .Call(`_simex_dust2_filter_simex_update_pars`, ptr, r_pars, r_index_group)
}

dust2_filter_simex_run <- function(ptr, r_initial, save_trajectories, save_snapshots, adjoint, index_state, index_group, preserve_particle_dimension, preserve_group_dimension) {
  .Call(`_simex_dust2_filter_simex_run`, ptr, r_initial, save_trajectories, save_snapshots, adjoint, index_state, index_group, preserve_particle_dimension, preserve_group_dimension)
}

dust2_filter_simex_last_trajectories <- function(ptr, select_random_particle, preserve_particle_dimension, preserve_group_dimension) {
  .Call(`_simex_dust2_filter_simex_last_trajectories`, ptr, select_random_particle, preserve_particle_dimension, preserve_group_dimension)
}

dust2_filter_simex_last_snapshots <- function(ptr, select_random_particle, preserve_particle_dimension, preserve_group_dimension) {
  .Call(`_simex_dust2_filter_simex_last_snapshots`, ptr, select_random_particle, preserve_particle_dimension, preserve_group_dimension)
}

dust2_filter_simex_last_state <- function(ptr, select_random_particle, preserve_particle_dimension, preserve_group_dimension) {
  .Call(`_simex_dust2_filter_simex_last_state`, ptr, select_random_particle, preserve_particle_dimension, preserve_group_dimension)
}

dust2_filter_simex_rng_state <- function(ptr) {
  .Call(`_simex_dust2_filter_simex_rng_state`, ptr)
}

dust2_filter_simex_set_rng_state <- function(ptr, r_rng_state) {
  .Call(`_simex_dust2_filter_simex_set_rng_state`, ptr, r_rng_state)
}

dust2_system_tst_alloc <- function(r_pars, r_time, r_time_control, r_n_particles, r_n_groups, r_seed, r_deterministic, r_n_threads) {
  .Call(`_simex_dust2_system_tst_alloc`, r_pars, r_time, r_time_control, r_n_particles, r_n_groups, r_seed, r_deterministic, r_n_threads)
}

dust2_system_tst_run_to_time <- function(ptr, r_time) {
  .Call(`_simex_dust2_system_tst_run_to_time`, ptr, r_time)
}

dust2_system_tst_state <- function(ptr, r_index_state, r_index_particle, r_index_group, preserve_particle_dimension, preserve_group_dimension) {
  .Call(`_simex_dust2_system_tst_state`, ptr, r_index_state, r_index_particle, r_index_group, preserve_particle_dimension, preserve_group_dimension)
}

dust2_system_tst_time <- function(ptr) {
  .Call(`_simex_dust2_system_tst_time`, ptr)
}

dust2_system_tst_set_state_initial <- function(ptr) {
  .Call(`_simex_dust2_system_tst_set_state_initial`, ptr)
}

dust2_system_tst_set_state <- function(ptr, r_state) {
  .Call(`_simex_dust2_system_tst_set_state`, ptr, r_state)
}

dust2_system_tst_reorder <- function(ptr, r_index) {
  .Call(`_simex_dust2_system_tst_reorder`, ptr, r_index)
}

dust2_system_tst_rng_state <- function(ptr) {
  .Call(`_simex_dust2_system_tst_rng_state`, ptr)
}

dust2_system_tst_set_rng_state <- function(ptr, r_rng_state) {
  .Call(`_simex_dust2_system_tst_set_rng_state`, ptr, r_rng_state)
}

dust2_system_tst_set_time <- function(ptr, r_time) {
  .Call(`_simex_dust2_system_tst_set_time`, ptr, r_time)
}

dust2_system_tst_update_pars <- function(ptr, pars) {
  .Call(`_simex_dust2_system_tst_update_pars`, ptr, pars)
}

dust2_system_tst_simulate <- function(ptr, r_times, r_index_state, preserve_particle_dimension, preserve_group_dimension) {
  .Call(`_simex_dust2_system_tst_simulate`, ptr, r_times, r_index_state, preserve_particle_dimension, preserve_group_dimension)
}

dust2_unfilter_tst_alloc <- function(r_pars, r_time_start, r_time, r_time_control, r_data, r_n_particles, r_n_groups, r_n_threads) {
  .Call(`_simex_dust2_unfilter_tst_alloc`, r_pars, r_time_start, r_time, r_time_control, r_data, r_n_particles, r_n_groups, r_n_threads)
}

dust2_filter_tst_alloc <- function(r_pars, r_time_start, r_time, r_time_control, r_data, r_n_particles, r_n_groups, r_n_threads, r_seed) {
  .Call(`_simex_dust2_filter_tst_alloc`, r_pars, r_time_start, r_time, r_time_control, r_data, r_n_particles, r_n_groups, r_n_threads, r_seed)
}

dust2_system_tst_compare_data <- function(ptr, r_data, preserve_particle_dimension, preserve_group_dimension) {
  .Call(`_simex_dust2_system_tst_compare_data`, ptr, r_data, preserve_particle_dimension, preserve_group_dimension)
}

dust2_unfilter_tst_update_pars <- function(ptr, r_pars, r_index_group) {
  .Call(`_simex_dust2_unfilter_tst_update_pars`, ptr, r_pars, r_index_group)
}

dust2_unfilter_tst_run <- function(ptr, r_initial, save_trajectories, save_snapshots, adjoint, r_index_state, r_index_group, preserve_particle_dimension, preserve_group_dimension) {
  .Call(`_simex_dust2_unfilter_tst_run`, ptr, r_initial, save_trajectories, save_snapshots, adjoint, r_index_state, r_index_group, preserve_particle_dimension, preserve_group_dimension)
}

dust2_unfilter_tst_last_trajectories <- function(ptr, select_random_particle, preserve_particle_dimension, preserve_group_dimension) {
  .Call(`_simex_dust2_unfilter_tst_last_trajectories`, ptr, select_random_particle, preserve_particle_dimension, preserve_group_dimension)
}

dust2_unfilter_tst_last_snapshots <- function(ptr, select_random_particle, preserve_particle_dimension, preserve_group_dimension) {
  .Call(`_simex_dust2_unfilter_tst_last_snapshots`, ptr, select_random_particle, preserve_particle_dimension, preserve_group_dimension)
}

dust2_unfilter_tst_last_state <- function(ptr, select_random_particle, preserve_particle_dimension, preserve_group_dimension) {
  .Call(`_simex_dust2_unfilter_tst_last_state`, ptr, select_random_particle, preserve_particle_dimension, preserve_group_dimension)
}

dust2_filter_tst_update_pars <- function(ptr, r_pars, r_index_group) {
  .Call(`_simex_dust2_filter_tst_update_pars`, ptr, r_pars, r_index_group)
}

dust2_filter_tst_run <- function(ptr, r_initial, save_trajectories, save_snapshots, adjoint, index_state, index_group, preserve_particle_dimension, preserve_group_dimension) {
  .Call(`_simex_dust2_filter_tst_run`, ptr, r_initial, save_trajectories, save_snapshots, adjoint, index_state, index_group, preserve_particle_dimension, preserve_group_dimension)
}

dust2_filter_tst_last_trajectories <- function(ptr, select_random_particle, preserve_particle_dimension, preserve_group_dimension) {
  .Call(`_simex_dust2_filter_tst_last_trajectories`, ptr, select_random_particle, preserve_particle_dimension, preserve_group_dimension)
}

dust2_filter_tst_last_snapshots <- function(ptr, select_random_particle, preserve_particle_dimension, preserve_group_dimension) {
  .Call(`_simex_dust2_filter_tst_last_snapshots`, ptr, select_random_particle, preserve_particle_dimension, preserve_group_dimension)
}

dust2_filter_tst_last_state <- function(ptr, select_random_particle, preserve_particle_dimension, preserve_group_dimension) {
  .Call(`_simex_dust2_filter_tst_last_state`, ptr, select_random_particle, preserve_particle_dimension, preserve_group_dimension)
}

dust2_filter_tst_rng_state <- function(ptr) {
  .Call(`_simex_dust2_filter_tst_rng_state`, ptr)
}

dust2_filter_tst_set_rng_state <- function(ptr, r_rng_state) {
  .Call(`_simex_dust2_filter_tst_set_rng_state`, ptr, r_rng_state)
}
