## Generated by dust2 (version 0.3.28) - do not edit
simex <- structure(
  function() get("simex"),
  class = "dust_system_generator",
  name = "simex",
  package = "simex",
  path = NULL,
  parameters = data.frame(
    name = c("n_age", "N", "hosp_capacity", "vax_rate", "vax_prioritised", "hosp_prioritised", "vax_infectiousness", "vax_infection", "vax_hosp", "vax_death", "prop_hosp", "hosp_mortality", "unhosp_mortality", "hosp_duration", "comm_mortality", "symptomatic_period", "incubation_period", "p_trans", "kappa_E", "kappa_C", "kappa_H", "init_state"),
    type = c("int", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type"),
    constant = c(TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE),
    required = c(TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE),
    rank = c(0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 1L, 1L, 1L, 1L, 1L, 0L, 0L, 0L, 2L, 2L, 2L, 2L)),
  properties = list(
    time_type = "discrete",
    has_compare = TRUE,
    has_adjoint = FALSE),
  default_dt = 1)
