#' Calculate next-gen (and other) matrices used for R0 and r calculations: these
#' assume a completely susceptible population and no interventions!
#'
#' @param p_trans Probability of infection per contacts.
#' @param pars A set of parameters as returned by \code{get_parameters}.
#'
get_matrices <- function(p_trans, pars) {

  nr <- length(pars$age_frac)

  ## these are new infections (E_u to E_u, C_u to E_u, I_h to E_u) (filling by column)
  T <- cbind(
    ## E generate E with contact_rate*p_transmission*infectiousness_ratio
    rbind(t(p_trans * pars$infectiousness_presymp * pars$polymod$all), diag(0, nr), diag(0, nr)),
    ## I_c generate E with contact_rate*p_transmission
    rbind(t(p_trans*pars$polymod$all), diag(0, nr), diag(0, nr)),
    ## I_h generate E with contact_rate*p_transmission using ONLY other contacts
    rbind(t(p_trans*pars$polymod$other), diag(0, nr), diag(0, nr))
  )

  ## these are the transitions (filling by column) of individuals between
  ## categories (lots of zeroes because no transitions between age-groups)
  Eps <- cbind(
    rbind(-diag(pars$lambda_cu + pars$lambda_hu, nr),
          diag(pars$lambda_cu, nr),
          diag(pars$lambda_hu, nr)),
    rbind(diag(0, nr), -diag(pars$sigma_cu + pars$mu_cu, nr), diag(0, nr)),
    rbind(diag(0, nr), diag(0, nr), -diag(pars$sigma_hu + pars$mu_hu, nr))
  )

  ## average future time spent by index j in index i
  Eps_inv <- cbind(
    rbind(
      ## E will spend in E given by inverse of the rates leave into I_h and I_c
      diag(1/(pars$lambda_cu + pars$lambda_hu), nr),
      ## average future time spent by E in I_c: the first part is the duration
      ## I_c spends in the community, the second part is the proportion of E
      ## that go into I-c
      diag(
        1/(pars$sigma_cu + pars$mu_cu) * pars$lambda_cu/(pars$lambda_cu + pars$lambda_hu),
        nr
      ),
      ## average future time spent by E in I_h
      diag(
        1/(pars$sigma_hu + pars$mu_hu)*pars$lambda_hu/(pars$lambda_cu + pars$lambda_hu),
        nr
      )
    ),
    ## I_c spends symptomatic_period in community
    rbind(diag(0, nr), diag(1/(pars$sigma_cu + pars$mu_cu), nr), diag(0, nr)),
    ## I_h spends hosp_duration in community
    rbind(diag(0, nr), diag(0, nr), diag(1/(pars$sigma_hu + pars$mu_hu), nr))
  )

  ## calculate the mean "age" of infections caused by each compartment
  age_E <- if(length(pars$incubation_period) == 1)
             rep(pars$incubation_period, nr)/2
           else pars$incubation_period/2
  age_C <- pars$incubation_period +
    if(length(pars$symptomatic_period) == 1)
      rep(pars$symptomatic_period, nr)/2
    else pars$symptomatic_period/2
  age_H <- pars$incubation_period +
    if(length(pars$hosp_duration) == 1) rep(pars$hosp_duration, nr)/2
    else pars$hosp_duration/2
  ages <- c(age_E, age_C, age_H)

  ## The RHS multiplies the days spent by j in i times the average age of the
  ## case they would generate. The matrix multiplication operator then
  ## incorporates the force of infection (i.e. daily infections caused): if j
  ## spends 5 days in i, the average age caused is 7 days, and infects on
  ## average 2 cases per day, the total "age days" generated by j in i in 5*7*2
  ## = 70. The matrix multiplication operator then sums across the infector j to
  ## give the total "age days" it contributes to compartment i over the course
  ## of it's lifetime.
  agesums <- T %*% apply(Eps_inv, 2, \(x) x * ages)

  ## This looks just at change and is used for r
  delta <- T + Eps

  ## This gives new infections and is used for R0
  ngm <- T %*% Eps_inv

  list(T = T, Eps = Eps, Eps_inv = Eps_inv, delta = delta, ngm = ngm, agesums = agesums)

}


#' Calculate R0 as the principal eigenvalue of the next-generation matrix.
#'
#' @param p_trans Probability of infection per contacts.
#' @param pars A set of parameters as returned by \code{get_parameters}.
#'
get_R0 <- function(p_trans, pars) max(Re(eigen(get_matrices(p_trans, pars)$ngm)$values))

#' Calculate the exponential growth rate as the principal eigenvalue of the
#' change in exposed.
#'
#' @param p_trans Probability of infection per contacts.
#' @param pars A set of parameters as returned by \code{get_parameters}.
#'
get_r <- function(p_trans, pars) max(Re(eigen(get_matrices(p_trans, pars)$delta)$values))

#' The sum of "ages" of infections caused by each compartment in each
#' compartment.
#'
#' @param p_trans Probability of infection per contacts.
#' @param pars A set of parameters as returned by \code{get_parameters}.
#'
get_agesums <- function(p_trans, pars) max(Re(eigen(get_matrices(p_trans, pars)$agesums)$values))

#' The doubling is calculated from the exponential growth rate.
#'
#' @param p_trans Probability of infection per contacts.
#' @param pars A set of parameters as returned by \code{get_parameters}.
#'
get_doubling_time <- function(p_trans, pars) log(2)/get_r(p_trans, pars)

#' The mean generation time is calculated as the sum of "ages" of cases caused
#' divided by the number of cases caused.
#'
#' @param p_trans Probability of infection per contacts.
#' @param pars A set of parameters as returned by \code{get_parameters}.
#'
get_generation_time <- function(p_trans, pars) {
  mat <- get_matrices(p_trans, pars)
  max(Re(eigen(mat$agesums)$values))/max(Re(eigen(mat$ngm)$values))
}

